Repository Royal-Navy/design-system, pull requests merged in 2019-04, with the labels that each got.

#1 Toggle
  packages/css-framework/index.scss
  packages/css-framework/src/components/_toggle.scss
  packages/documentation/library/pages/develop/components/images/toggle.png
  packages/documentation/library/pages/develop/components/toggle.md
  packages/vue-component-library/src/components/RnToggle/RnToggle.spec.js
  packages/vue-component-library/src/components/RnToggle/RnToggle.stories.js
  packages/vue-component-library/src/components/RnToggle/index.vue
  packages/vue-component-library/src/components/RnToggle/scripts.js
Labels: enhancement

#3 EN-520 : Address linting errors
  .circleci/config.yml
  package.json
  packages/css-framework/index.scss
  packages/css-framework/package.json
  packages/css-framework/prettier.config.js
  packages/vue-component-library/src/components/RnAlert/RnAlert.spec.js
  yarn.lock
Labels: bug

#8 Address security vulnerability in js-yaml
  package.json
  packages/vue-component-library/package.json
  yarn.lock
Labels: Security

#7 Adjust jest to output coverage in circle
  .circleci/config.yml
Labels: Devops

#11 updated ciconfig to attempt to fix pipefail bug
  .circleci/config.yml
Labels: bug
