Repository Royal-Navy/design-system, pull requests merged in 2019-08, with the labels that each got.

#186 Feature/EN-743 migrate monorepo to lerna
  README.md
  docs/definition_of_done.md
  docs/release_checklist.md
  lerna.json
  package.json
  packages/eslint-config-react/package.json
  scripts/syncversion.js
  yarn.lock
Labels: devops, enhancement

#189 1.0.2
  README.md
  docs/definition_of_done.md
  docs/release_checklist.md
  lerna.json
  package.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/docs-site/src/library/images/components/nav/anatomy.svg
  packages/docs-site/src/library/images/components/nav/component.svg
  packages/docs-site/src/library/images/components/nav/states.svg
  packages/docs-site/src/library/pages/components/nav.md
  packages/docs-site/src/library/pages/get-started/development/index.md
  packages/eslint-config-react/package.json
  packages/react-component-library/package.json
  packages/storybook-react-input-state/package.json
  packages/vue-component-library/package.json
  scripts/syncversion.js
  yarn.lock
Labels: release

#182 EN-739 sidebar touch bugs
  packages/css-framework/src/fragments/_sidebar.scss
  packages/react-component-library/src/components/Link/index.tsx
  packages/react-component-library/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/react-component-library/src/fragments/Sidebar/Sidebar.stories.tsx
  packages/react-component-library/src/fragments/Sidebar/index.tsx
Labels: bug

#196 Fix bug with Breadcrumb type definition
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumb.tsx
  packages/react-component-library/src/components/Breadcrumbs/index.tsx
Labels: bug

#198 Feature/EN-762 decouple formik from textinput
  packages/css-framework/index.scss
  packages/css-framework/src/components/_textinput.scss
  packages/css-framework/src/fragments/_form.scss
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/components/TextInput/TextInput.test.tsx
  packages/react-component-library/src/components/TextInput/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/enhancers/withFormik.tsx
Labels: component, enhancement

#183 Feature/EN-741 radio component
  images/Browserstack-logo.svg
  packages/css-framework/index.scss
  packages/css-framework/src/components/_radio.scss
  packages/docs-site/src/library/images/components/forms/radio/anatomy.svg
  packages/docs-site/src/library/images/components/forms/radio/component.svg
  packages/docs-site/src/library/images/components/forms/radio/states.svg
  packages/docs-site/src/library/pages/components/forms/radio.md
  packages/react-component-library/src/components/Radio/Radio.stories.tsx
  packages/react-component-library/src/components/Radio/Radio.test.tsx
  packages/react-component-library/src/components/Radio/index.tsx
  packages/react-component-library/src/index.ts
Labels: component, documentation, enhancement

#191 Feature/EN-742 checkbox component
  packages/css-framework/src/components/_checkbox.scss
  packages/docs-site/src/library/images/components/forms/checkbox/anatomy.svg
  packages/docs-site/src/library/images/components/forms/checkbox/component.svg
  packages/docs-site/src/library/images/components/forms/checkbox/states.svg
  packages/docs-site/src/library/pages/components/forms/checkbox.md
  packages/react-component-library/src/components/Checkbox/Checkbox.stories.tsx
  packages/react-component-library/src/components/Checkbox/Checkbox.test.tsx
  packages/react-component-library/src/components/Checkbox/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, documentation, enhancement

#211 Bugfix/Spelling error on Nav docs site page
  packages/docs-site/src/library/pages/components/nav.md
Labels: bug, documentation

#213 Bugfix/Remove dead feedback link from footer
  packages/docs-site/src/components/presenters/footer/index.js
Labels: bug, documentation

#215 Bugfix/Fix incorrect path in quick start
  packages/docs-site/src/library/pages/get-started/development/installation.md
Labels: bug, documentation

#217 Bugfix/Remove redundant test
  packages/docs-site/src/components/presenters/footer/index.test.js
Labels: bug

#228 Add storybook:static task
  package.json
  packages/react-component-library/.gitignore
  packages/react-component-library/package.json
Labels: devops, enhancement

#231 1.1.0
  .github/ISSUE_TEMPLATE/new-component-design-and-build.md
  images/Browserstack-logo.svg
  lerna.json
  package.json
  packages/css-framework/index.scss
  packages/css-framework/package.json
  packages/css-framework/src/components/_checkbox.scss
  packages/css-framework/src/components/_radio.scss
  packages/css-framework/src/components/_textinput.scss
  packages/css-framework/src/fragments/_form.scss
  packages/css-framework/src/fragments/_sidebar.scss
  packages/docs-site/package.json
  packages/docs-site/src/components/presenters/footer/index.js
  packages/docs-site/src/components/presenters/footer/index.test.js
  packages/docs-site/src/library/images/components/forms/checkbox/anatomy.svg
  packages/docs-site/src/library/images/components/forms/checkbox/component.svg
  packages/docs-site/src/library/images/components/forms/checkbox/states.svg
  packages/docs-site/src/library/images/components/forms/radio/anatomy.svg
  packages/docs-site/src/library/images/components/forms/radio/component.svg
  packages/docs-site/src/library/images/components/forms/radio/states.svg
  packages/docs-site/src/library/pages/components/forms/checkbox.md
  packages/docs-site/src/library/pages/components/forms/radio.md
  packages/docs-site/src/library/pages/components/nav.md
  packages/docs-site/src/library/pages/get-started/development/installation.md
  packages/eslint-config-react/package.json
  packages/react-component-library/.gitignore
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumb.tsx
  packages/react-component-library/src/components/Breadcrumbs/index.tsx
  packages/react-component-library/src/components/Checkbox/Checkbox.stories.tsx
  packages/react-component-library/src/components/Checkbox/Checkbox.test.tsx
  packages/react-component-library/src/components/Checkbox/index.tsx
  packages/react-component-library/src/components/Link/index.tsx
  packages/react-component-library/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/react-component-library/src/components/Radio/Radio.stories.tsx
  packages/react-component-library/src/components/Radio/Radio.test.tsx
  packages/react-component-library/src/components/Radio/index.tsx
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/components/TextInput/TextInput.test.tsx
  packages/react-component-library/src/components/TextInput/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/enhancers/withFormik.tsx
  packages/react-component-library/src/fragments/Sidebar/Sidebar.stories.tsx
  packages/react-component-library/src/fragments/Sidebar/index.tsx
  packages/react-component-library/src/index.ts
  packages/storybook-react-input-state/package.json
  packages/vue-component-library/package.json
Labels: release

#200 Migrate from Firebase to Netlify
  README.md
Labels: devops

#233 Bugfix/docs site fixes
  packages/docs-site/src/library/pages/components/button.md
  packages/docs-site/src/library/pages/components/forms/index.md
  packages/docs-site/src/library/pages/components/phase-banner.md
  packages/docs-site/src/library/pages/styles/container.md
Labels: Docs Site, bug

#234 1.1.1
  README.md
  docs/release_checklist.md
  lerna.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/components/button.md
  packages/docs-site/src/library/pages/components/forms/index.md
  packages/docs-site/src/library/pages/components/phase-banner.md
  packages/docs-site/src/library/pages/styles/container.md
  packages/eslint-config-react/package.json
  packages/react-component-library/package.json
  packages/storybook-react-input-state/package.json
  packages/vue-component-library/package.json
Labels: release

#245 Bugfix/add formik enhancer exports
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/enhancers/index.tsx
  packages/react-component-library/src/index.ts
  packages/react-component-library/tsconfig.json
Labels: bug
