Repository Royal-Navy/design-system, pull requests merged in 2019-06, with the labels that each got.

#51 Feature/sidebar navigation
  packages/docs-site/src/components/enhancers/withNavigation.js
  packages/docs-site/src/components/presenters/sidebar/__snapshots__/index.test.js.snap
  packages/docs-site/src/components/presenters/sidebar/index.js
  packages/docs-site/src/components/presenters/sidebar/index.test.js
  packages/docs-site/src/components/presenters/sidebar/sidebar.scss
  packages/docs-site/src/templates/default.js
Labels: enhancement

#53 Use yarn instead of npm to run the build
  .circleci/config.yml
Labels: bug

#54 Build local dependencies as part of build_docs-site job
  .circleci/config.yml
Labels: bug

#55 Target node with WebPack build instead of browser
  packages/react-component-library/webpack/common.js
Labels: bug

#56 Fix storybook build after changing target to node for react components
  packages/react-component-library/.storybook/webpack.config.js
Labels: bug

#57 EN-619 TextInput
  packages/css-framework/index.scss
  packages/css-framework/src/components/_button.scss
  packages/css-framework/src/components/_input.scss
  packages/css-framework/src/components/_textinput.scss
  packages/react-component-library/.eslintrc.js
  packages/react-component-library/.storybook/preview-head.html
  packages/react-component-library/.storybook/styles.css
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Button/index.tsx
  packages/react-component-library/src/components/TextInput/README.md
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/components/TextInput/TextInput.test.tsx
  packages/react-component-library/src/components/TextInput/images/input-examples.png
  packages/react-component-library/src/components/TextInput/index.tsx
  packages/react-component-library/src/icons/Search.tsx
  packages/react-component-library/src/icons/index.ts
  packages/react-component-library/src/types/FieldProps.d.ts
  packages/react-component-library/src/types/FormProps.d.ts
  yarn.lock
Labels: enhancement

#60 Improve markup semantics
  packages/docs-site/src/components/presenters/sketch-widget/index.js
Labels: enhancement

#61 Export icons from React component library
  packages/react-component-library/src/components/Button/Button.stories.tsx
  packages/react-component-library/src/components/Nav/Nav.stories.tsx
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/icons/index.ts
  packages/react-component-library/src/index.ts
Labels: enhancement

#65 Adjust sidebar navigation styles
  packages/docs-site/src/components/presenters/sidebar/sidebar.scss
Labels: bug

#58 Feature/code highlighter
  packages/docs-site/jest/__mocks__/client.js
  packages/docs-site/package.json
  packages/docs-site/src/components/presenters/code-highlighter/code-highlighter.scss
  packages/docs-site/src/components/presenters/code-highlighter/copy-icon.svg
  packages/docs-site/src/components/presenters/code-highlighter/index.js
  packages/docs-site/src/components/presenters/code-highlighter/index.test.js
  packages/docs-site/src/components/presenters/code-highlighter/theme.scss
  packages/docs-site/src/templates/default.js
  yarn.lock
Labels: enhancement

#59 Feature/card
  packages/docs-site/src/components/presenters/card/arrow-right-icon.svg
  packages/docs-site/src/components/presenters/card/card.scss
  packages/docs-site/src/components/presenters/card/index.js
  packages/docs-site/src/components/presenters/card/index.test.js
Labels: enhancement

#68 Check document object exists
  packages/docs-site/src/components/presenters/code-highlighter/index.js
Labels: bug

#69 Bugfix/make docs site ci more robust
  .circleci/config.yml
  packages/docs-site/src/components/presenters/code-highlighter/index.js
Labels: bug, enhancement

#67 EN-588 Masthead
  packages/css-framework/index.scss
  packages/css-framework/src/components/_masthead.scss
  packages/docs-site/.eslintrc.js
  packages/docs-site/package.json
  packages/docs-site/src/components/presenters/Masthead/images/site-logo.svg
  packages/docs-site/src/components/presenters/Masthead/index.js
  packages/docs-site/src/components/presenters/Masthead/masthead.scss
  packages/docs-site/src/components/presenters/TextInput/index.js
Labels: enhancement

#70 EN-655 Doc site layout
  packages/css-framework/src/contexts/_light.scss
  packages/docs-site/src/components/presenters/Masthead/index.js
  packages/docs-site/src/components/presenters/Masthead/masthead.scss
  packages/docs-site/src/components/presenters/footer/footer.scss
  packages/docs-site/src/templates/default.js
  packages/docs-site/src/templates/default.scss
Labels: enhancement

#71 Import fonts into default layout
  packages/docs-site/src/templates/default.js
Labels: enhancement

#72 Update dependencies
  deprecated/react-component-library/package.json
  deprecated/react-component-library/webpack/webpack.common.js
  packages/docs-site/package.json
  packages/html-storybook/package.json
  packages/html-storybook/webpack/webpack.common.js
  packages/react-component-library/package.json
  packages/react-component-library/webpack/prod.js
  packages/storybook-react-input-state/package.json
  packages/storybook-react-input-state/webpack/webpack.common.js
  packages/vue-component-library/package.json
  yarn.lock
Labels: Devops

#74 EN-665 Populate primary nav
  packages/docs-site/jest/__mocks__/gatsby.js
  packages/docs-site/jest/data/mockNavData.js
  packages/docs-site/src/components/enhancers/withNavigation.js
  packages/docs-site/src/components/presenters/Masthead/Masthead.test.js
  packages/docs-site/src/components/presenters/Masthead/index.js
  packages/docs-site/src/hooks/usePrimaryNavData.js
  packages/docs-site/src/hooks/usePrimaryNavData.test.js
  packages/docs-site/src/templates/default.js
  packages/docs-site/src/utils/nav.js
  packages/react-component-library/src/components/Button/index.tsx
Labels: enhancement

#75 EN-666 Left navigation
  packages/docs-site/src/components/enhancers/.gitkeep
  packages/docs-site/src/components/enhancers/withNavigation.js
  packages/docs-site/src/components/presenters/sidebar/index.js
  packages/docs-site/src/components/presenters/sidebar/index.test.js
  packages/docs-site/src/hooks/index.js
  packages/docs-site/src/hooks/useNavigationQuery.js
  packages/docs-site/src/hooks/usePrimaryNavData.js
  packages/docs-site/src/hooks/useSecondaryNavData.js
  packages/docs-site/src/hooks/useSecondaryNavData.test.js
  packages/docs-site/src/templates/default.js
Labels: enhancement

#79 Enable MDX usage
  packages/docs-site/gatsby-config.js
  packages/docs-site/package.json
  yarn.lock
Labels: enhancement

#73 Feature/en 531 docs site table component
  packages/docs-site/src/components/presenters/data-table/data-table.scss
  packages/docs-site/src/components/presenters/data-table/down-arrow-icon.svg
  packages/docs-site/src/components/presenters/data-table/index.js
  packages/docs-site/src/components/presenters/data-table/index.test.js
  packages/docs-site/src/components/presenters/data-table/table-body.js
  packages/docs-site/src/components/presenters/data-table/table-cell.js
  packages/docs-site/src/components/presenters/data-table/table-head.js
  packages/docs-site/src/components/presenters/data-table/table-row.js
  packages/docs-site/src/helpers/css/fonts.css
  packages/docs-site/src/helpers/fonts/RobotoMono-Regular.ttf
  packages/docs-site/src/helpers/fonts/source-code-pro-v9-latin-600.eot
  packages/docs-site/src/helpers/fonts/source-code-pro-v9-latin-600.svg
  packages/docs-site/src/helpers/fonts/source-code-pro-v9-latin-600.ttf
  packages/docs-site/src/helpers/fonts/source-code-pro-v9-latin-600.woff
  packages/docs-site/src/helpers/fonts/source-code-pro-v9-latin-600.woff2
Labels: enhancement

#76 Feature/en 558 tab set component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_tab-set.scss
  packages/react-component-library/jest/__mocks__/uuid.js
  packages/react-component-library/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/react-component-library/src/components/TabSet/README.md
  packages/react-component-library/src/components/TabSet/TabSet.stories.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
  packages/react-component-library/src/components/TabSet/images/tabset.png
  packages/react-component-library/src/components/TabSet/index.tsx
Labels: enhancement

#86 Feature/convert from remark to mdx
  packages/docs-site/gatsby-config.js
  packages/docs-site/gatsby-node.js
  packages/docs-site/jest/data/mockNavData.js
  packages/docs-site/package.json
  packages/docs-site/src/components/presenters/post-article/index.js
  packages/docs-site/src/components/presenters/post-article/index.test.js
  packages/docs-site/src/components/presenters/post-article/post-md.scss
  packages/docs-site/src/hooks/useNavigationQuery.js
  packages/docs-site/src/templates/default.js
  packages/react-component-library/src/components/Nav/README.md
  yarn.lock
Labels: enhancement

#88 Feature/odds and ends
  packages/html-storybook/src/components/Nav/Nav.stories.js
  packages/react-component-library/.storybook/preview-head.html
  packages/react-component-library/jest.config.js
  packages/react-component-library/jest/__mocks__/fileMock.js
  packages/react-component-library/src/components/Button/Button.stories.tsx
  packages/react-component-library/src/components/Nav/Nav.stories.tsx
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/icons/index.ts
  packages/react-component-library/src/index.ts
Labels: bug

#89 EN-653 Breadcrumb
  deprecated/react-component-library/src/components/Nav/README.md
  packages/css-framework/index.scss
  packages/css-framework/src/components/_breadcrumbs.scss
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumb.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  packages/react-component-library/src/components/Breadcrumbs/EndTitle.tsx
  packages/react-component-library/src/components/Breadcrumbs/README.md
  packages/react-component-library/src/components/Breadcrumbs/images/breadcrumbs.png
  packages/react-component-library/src/components/Breadcrumbs/images/links.png
  packages/react-component-library/src/components/Breadcrumbs/images/separator.svg
  packages/react-component-library/src/components/Breadcrumbs/index.tsx
  packages/react-component-library/src/components/Link/index.tsx
  packages/react-component-library/src/components/Links/LinkItem.tsx
  packages/react-component-library/src/components/Links/README.md
  packages/react-component-library/src/components/Nav/README.md
Labels: enhancement

#91 Fix alignment of docs site (EN-689) and introduce common container style (EN-659)
  deprecated/react-component-library/src/components/PhaseBanner/index.js
  packages/css-framework/src/components/_container.scss
  packages/css-framework/src/components/_phase-banner.scss
  packages/docs-site/src/components/presenters/Masthead/index.js
  packages/docs-site/src/components/presenters/Masthead/masthead.scss
  packages/docs-site/src/components/presenters/footer/footer.scss
  packages/docs-site/src/components/presenters/footer/index.js
  packages/docs-site/src/templates/default.js
  packages/docs-site/src/templates/default.scss
  packages/react-component-library/src/components/PhaseBanner/index.tsx
Labels: bug, enhancement

#92 Rename Button.mdx to Button.md
  packages/documentation/library/pages/components/button.md
Labels: bug

#96 Feature/EN-694 add consolidate-docs:watch task
  packages/docs-site/package.json
  yarn.lock
Labels: enhancement

#97 Feature/en 696 use children instead of prop for codehighlighter previews
  packages/docs-site/src/components/presenters/code-highlighter/index.js
  packages/docs-site/src/components/presenters/code-highlighter/index.test.js
Labels: enhancement
