Repository Royal-Navy/design-system, pull requests merged in 2019-12, with the labels that each got.

#458 Add versions page
  packages/docs-site/src/library/pages/versions.md
Labels: Docs Site, enhancement

#462 Add version badge to docs site masthead
  packages/docs-site/src/components/presenters/Masthead/Masthead.test.js
  packages/docs-site/src/components/presenters/Masthead/index.js
  packages/docs-site/src/components/presenters/Masthead/masthead.scss
Labels: Docs Site, enhancement

#463 Update "Latest updates" section on docs site
  packages/docs-site/src/library/pages/index.md
Labels: Docs Site, enhancement

#464 Remove duplicate CSS
  packages/css-framework/src/components/_tab-set.scss
Labels: component

#480 Upgrade dependencies
  package.json
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/components/button.md
  packages/eslint-config-react/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Button/Button.test.tsx
  packages/react-component-library/src/components/Button/Button.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.test.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
  packages/react-component-library/src/components/TextArea/TextArea.test.tsx
  packages/react-component-library/src/components/TextArea/index.tsx
  packages/react-component-library/src/components/TextInput/TextInput.test.tsx
  packages/react-component-library/src/components/TextInput/index.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/react-component-library/src/hooks/useFocus.ts
  packages/reactapp/package.json
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: devops, security

#476 Add variant prop to avatar
  packages/docs-site/src/library/pages/components/avatar.md
  packages/react-component-library/src/components/Avatar/Avatar.stories.tsx
  packages/react-component-library/src/components/Avatar/Avatar.tsx
  packages/react-component-library/src/components/Avatar/constants.ts
  packages/react-component-library/src/components/Avatar/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/fragments/Masthead/UserLink.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notification.tsx
  packages/react-component-library/src/index.ts
Labels: component, enhancement

#477 Delete redundant README files
  packages/react-component-library/src/components/Badge/README.md
  packages/react-component-library/src/components/Badge/images/badge-faded.png
  packages/react-component-library/src/components/Badge/images/badge-pills.png
  packages/react-component-library/src/components/Badge/images/badge-sizes.png
  packages/react-component-library/src/components/Badge/images/badge-solid.png
  packages/react-component-library/src/components/Breadcrumbs/README.md
  packages/react-component-library/src/components/Breadcrumbs/images/breadcrumbs.png
  packages/react-component-library/src/components/Breadcrumbs/images/links.png
  packages/react-component-library/src/components/Button/README.md
  packages/react-component-library/src/components/Button/images/button-icon.png
  packages/react-component-library/src/components/Button/images/button-size.png
  packages/react-component-library/src/components/Button/images/button-variants.png
  packages/react-component-library/src/components/Nav/README.md
  packages/react-component-library/src/components/Nav/images/nav-horizontal.png
  packages/react-component-library/src/components/Nav/images/nav-sizes.png
  packages/react-component-library/src/components/Nav/images/nav-vertical.png
  packages/react-component-library/src/components/Pagination/README.md
  packages/react-component-library/src/components/Pagination/images/pagination.png
  packages/react-component-library/src/components/PhaseBanner/README.md
  packages/react-component-library/src/components/PhaseBanner/images/phase-banner-example.gif
  packages/react-component-library/src/components/TextInput/README.md
  packages/react-component-library/src/components/TextInput/images/input-examples.png
Labels: component, enhancement

#479 Tidy up component interfaces (quick wins)
  packages/docs-site/src/library/pages/components/modal.md
  packages/docs-site/src/library/pages/components/table.md
  packages/react-component-library/src/components/Dropdown/DropdownLabel.test.tsx
  packages/react-component-library/src/components/Dropdown/DropdownLabel.tsx
  packages/react-component-library/src/components/Dropdown/DropdownOption.ts
  packages/react-component-library/src/components/Modal/Modal.tsx
  packages/react-component-library/src/components/Select/Option.tsx
  packages/react-component-library/src/components/TabSet/TabSet.stories.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
  packages/react-component-library/src/components/TabSet/TabSet.tsx
  packages/react-component-library/src/components/Table/Table.stories.tsx
  packages/react-component-library/src/components/Table/Table.test.tsx
  packages/react-component-library/src/components/Table/Table.tsx
  packages/react-component-library/src/components/Table/TableColumn.tsx
  packages/react-component-library/src/components/Table/constants.ts
  packages/react-component-library/src/components/Table/index.tsx
  packages/react-component-library/src/components/Table/useTableData.ts
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, enhancement

#483 Add documentation for versions page
  docs/deploy_documentation.md
  docs/release_checklist.md
  docs/update_versions_page.md
Labels: devops, enhancement

#489 Refactor ButtonGroup component
  packages/docs-site/src/library/pages/components/buttongroup.md
  packages/react-component-library/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/react-component-library/src/components/ButtonGroup/ButtonGroup.test.tsx
  packages/react-component-library/src/components/ButtonGroup/ButtonGroup.tsx
  packages/react-component-library/src/components/ButtonGroup/ButtonGroupItem.tsx
  packages/react-component-library/src/components/ButtonGroup/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, enhancement

#491 Deprecate Nav component
  packages/docs-site/src/library/pages/components/nav.md
  packages/react-component-library/src/components/Nav/Nav.test.tsx
  packages/react-component-library/src/components/Nav/index.tsx
Labels: component

#492 Refactor breadcrumbs
  packages/css-framework/src/components/_breadcrumbs.scss
  packages/docs-site/src/library/pages/components/breadcrumbs.md
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumb.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/react-component-library/src/components/Breadcrumbs/BreadcrumbsItem.tsx
  packages/react-component-library/src/components/Breadcrumbs/EndTitle.tsx
  packages/react-component-library/src/components/Breadcrumbs/index.tsx
  packages/react-component-library/src/components/Link/index.tsx
  packages/react-component-library/src/components/Nav/index.tsx
  packages/react-component-library/src/components/TabNav/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/fragments/Sidebar/Sidebar.stories.tsx
  packages/react-component-library/src/index.ts
Labels: component, enhancement

#493 Add startAdornment to NumberInput
  lerna.json
  packages/css-framework/package.json
  packages/css-framework/src/components/_numberinput.scss
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/components/form/number-input.md
  packages/docs-site/src/library/pages/versions.md
  packages/eslint-config-react/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
  packages/react-component-library/src/components/NumberInput/NumberInput.stories.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.test.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.tsx
  packages/reactapp/package.json
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: component, enhancement

#499 Refactor Notifications to use Link
  packages/docs-site/src/library/pages/components/notifications.md
  packages/react-component-library/src/fragments/Masthead/Masthead.stories.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notification.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notification.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notifications.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notifications.tsx
  packages/react-component-library/src/fragments/Sidebar/Sidebar.stories.tsx
Labels: component, enhancement

#498 Refactor tab nav
  packages/css-framework/src/components/_tab-nav.scss
  packages/react-component-library/src/components/TabNav/TabNav.stories.tsx
  packages/react-component-library/src/components/TabNav/TabNav.test.tsx
  packages/react-component-library/src/components/TabNav/TabNav.tsx
  packages/react-component-library/src/components/TabNav/TabNavItem.tsx
  packages/react-component-library/src/components/TabNav/index.tsx
  packages/react-component-library/src/components/index.ts
Labels: component, enhancement

#497 Rename callback function prop
  packages/docs-site/src/library/pages/components/pagination.md
  packages/docs-site/src/library/pages/components/tab-set.md
  packages/react-component-library/src/components/Pagination/Pagination.stories.tsx
  packages/react-component-library/src/components/Pagination/Pagination.test.tsx
  packages/react-component-library/src/components/Pagination/index.tsx
  packages/react-component-library/src/components/Pagination/usePageChange.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
Labels: component, documentation, enhancement

#496 Change userprofile to user-profile
  packages/docs-site/src/library/pages/components/sidebar.md
Labels: component, documentation, enhancement

#495 Tighten up link prop on Breadcrumbs
  packages/react-component-library/src/components/Breadcrumbs/BreadcrumbsItem.tsx
Labels: component, enhancement
