Repository Royal-Navy/design-system, pull requests merged in 2019-11, with the labels that each got.

#399 ButtonGroup Component
  packages/css-framework/src/components/_btn-group.scss
  packages/docs-site/src/library/images/components/button-group/anatomy.svg
  packages/docs-site/src/library/images/components/button-group/component.svg
  packages/docs-site/src/library/pages/components/buttongroup.md
  packages/react-component-library/src/components/Button/Button.tsx
  packages/react-component-library/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/react-component-library/src/components/ButtonGroup/ButtonGroup.test.tsx
  packages/react-component-library/src/components/ButtonGroup/ButtonGroup.tsx
  packages/react-component-library/src/components/ButtonGroup/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: Atom, component

#404 Fixed bug in Select page in docs.
  packages/docs-site/src/library/pages/components/form/select.md
Labels: bug, documentation

#405 Update dependencies
  package.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/docs-site/plugins/gatsby-source-icon-parser/index.js
  packages/eslint-config-react/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
  packages/reactapp/package.json
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: devops

#368 Add sorting to table component
  packages/css-framework/src/components/_table.scss
  packages/docs-site/plugins/gatsby-source-icon-parser/gatsby-node.js
  packages/docs-site/plugins/gatsby-source-icon-parser/iconParser.js
  packages/docs-site/plugins/gatsby-source-icon-parser/searchRecursive.js
  packages/docs-site/prettier.config.js
  packages/docs-site/src/library/images/components/table/anatomy.svg
  packages/docs-site/src/library/images/components/table/component.svg
  packages/docs-site/src/library/pages/components/table.md
  packages/eslint-config-react/prettier.config.js
  packages/icon-library/src/assets/table/sort-ascending.svg
  packages/icon-library/src/assets/table/sort-descending.svg
  packages/icon-library/src/assets/table/sort-unsorted.svg
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Table/Column.tsx
  packages/react-component-library/src/components/Table/Table.stories.tsx
  packages/react-component-library/src/components/Table/Table.test.tsx
  packages/react-component-library/src/components/Table/Table.tsx
  packages/react-component-library/src/components/Table/constants.ts
  packages/react-component-library/src/components/Table/useTableData.ts
  yarn.lock
Labels: documentation, enhancement

#408 Devops/update release checklist
  docs/release_checklist.md
  docs/release_notes_template.md
Labels: enhancement

#270 Notification Component [WIP]
  packages/docs-site/src/library/images/components/notifications/anatomy.svg
  packages/docs-site/src/library/images/components/notifications/component.svg
  packages/docs-site/src/library/images/components/notifications/states.svg
  packages/docs-site/src/library/pages/components/notifications.md
Labels: Design - Signed Off, component, documentation

#406 Update notification panel content
  packages/css-framework/src/fragments/_notification-panel.scss
  packages/docs-site/src/library/pages/components/masthead.md
  packages/docs-site/src/library/pages/components/notifications.md
  packages/docs-site/src/library/pages/components/sidebar.md
  packages/react-component-library/package.json
  packages/react-component-library/src/fragments/Masthead/Masthead.stories.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.test.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notification.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notification.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notifications.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notifications.tsx
  packages/react-component-library/src/fragments/NotificationPanel/index.tsx
  packages/react-component-library/src/fragments/Sidebar/Sidebar.stories.tsx
  packages/react-component-library/src/fragments/Sidebar/index.tsx
  packages/react-component-library/src/index.ts
  yarn.lock
Labels: component, enhancement

#411 Fix button icon sizing issue
  packages/css-framework/src/components/_button.scss
  packages/css-framework/src/components/_modal.scss
  packages/icon-library/.svgrrc.js
  packages/icon-library/src/assets/arrows/button-confirm.svg
  packages/react-component-library/src/components/Button/Button.stories.tsx
  packages/react-component-library/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/react-component-library/src/components/Modal/Modal.tsx
Labels: bug, component

#414 Upgrade dependencies
  package.json
  packages/docs-site/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
  packages/reactapp/package.json
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: devops

#415 Upgrade node to 12 lts
  .circleci/config.yml
  .nvmrc
  package.json
  packages/docs-site/package.json
  packages/reactapp/.env
Labels: devops

#421 Add ability to mark documentation as draft
  packages/docs-site/gatsby-node.js
  packages/docs-site/src/hooks/useNavigationQuery.js
  packages/docs-site/src/library/pages/components/avatar.md
  packages/docs-site/src/utils/nav.js
Labels: Docs Site, documentation, enhancement

#422 Add missing import for SketchWidget
  packages/docs-site/src/library/pages/components/masthead.md
Labels: Docs Site, bug, documentation

#419 Refactor table sort order constants
  packages/react-component-library/src/components/Table/Column.tsx
  packages/react-component-library/src/components/Table/constants.ts
  packages/react-component-library/src/components/Table/useTableData.ts
Labels: Tech Debt, component

#417 Reuse CSS circle for notification panel indicator
  packages/css-framework/src/fragments/_notification-panel.scss
  packages/react-component-library/src/fragments/Masthead/Masthead.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notification.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/Notification.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.tsx
Labels: Tech Debt, component

#413 Add panel component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_panel.scss
  packages/docs-site/src/library/images/components/panel/component.svg
  packages/docs-site/src/library/pages/components/panel.md
  packages/react-component-library/src/components/Panel/Panel.stories.tsx
  packages/react-component-library/src/components/Panel/Panel.test.tsx
  packages/react-component-library/src/components/Panel/Panel.tsx
  packages/react-component-library/src/components/Panel/index.tsx
Labels: component

#425 Fix Dialog docs-site example positioning
  packages/docs-site/src/components/presenters/layout/globals.scss
Labels: Docs Site, bug, documentation

#403 RangeSlider Component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_range-slider.scss
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/components/range-slider.md
  packages/react-component-library/package.json
  packages/react-component-library/src/components/RangeSlider/Handle.tsx
  packages/react-component-library/src/components/RangeSlider/RangeSlider.stories.tsx
  packages/react-component-library/src/components/RangeSlider/RangeSlider.test.tsx
  packages/react-component-library/src/components/RangeSlider/Slider.tsx
  packages/react-component-library/src/components/RangeSlider/Tick.tsx
  packages/react-component-library/src/components/RangeSlider/Track.tsx
  packages/react-component-library/src/components/RangeSlider/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
  yarn.lock
Labels: component, enhancement

#429 Add default alert component
  packages/css-framework/src/components/_alert.scss
  packages/react-component-library/src/components/Alert/Alert.stories.tsx
  packages/react-component-library/src/components/Alert/Alert.test.tsx
  packages/react-component-library/src/components/Alert/Alert.tsx
  packages/react-component-library/src/components/Alert/constants.ts
  packages/react-component-library/src/components/Alert/index.tsx
Labels: component

#432 Set handlebars transitive dependency
  package.json
Labels: security

#431 Update label to correct value 000
  packages/docs-site/src/library/pages/styles/colours.md
Labels: bug

#430 Add alert variants
  packages/css-framework/src/components/_alert.scss
  packages/react-component-library/src/components/Alert/Alert.stories.tsx
  packages/react-component-library/src/components/Alert/Alert.test.tsx
  packages/react-component-library/src/components/Alert/Alert.tsx
  packages/react-component-library/src/components/Alert/constants.ts
Labels: component, enhancement

#424 Drawer Component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_drawer.scss
  packages/docs-site/src/library/images/components/drawer/anatomy.svg
  packages/docs-site/src/library/images/components/drawer/component.svg
  packages/docs-site/src/library/pages/components/drawer.md
  packages/react-component-library/src/components/Drawer/Drawer.stories.tsx
  packages/react-component-library/src/components/Drawer/Drawer.test.tsx
  packages/react-component-library/src/components/Drawer/Drawer.tsx
  packages/react-component-library/src/components/Drawer/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, enhancement

#433 Add alert component documentation
  packages/docs-site/src/library/images/components/alert/anatomy.svg
  packages/docs-site/src/library/images/components/alert/component.svg
  packages/docs-site/src/library/images/components/alert/states.svg
  packages/docs-site/src/library/pages/components/alert.md
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, documentation

#442 Devops/upgrade dependencies
  package.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/eslint-config-react/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
  packages/reactapp/package.json
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: devops, security

#440 Refactor tab set
  packages/react-component-library/src/components/TabSet/README.md
  packages/react-component-library/src/components/TabSet/Tab.tsx
  packages/react-component-library/src/components/TabSet/TabContent.tsx
  packages/react-component-library/src/components/TabSet/TabItem.tsx
  packages/react-component-library/src/components/TabSet/TabSet.stories.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
  packages/react-component-library/src/components/TabSet/TabSet.tsx
  packages/react-component-library/src/components/TabSet/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component

#445 Release/1.8.0
  lerna.json
  package.json
  packages/css-framework/index.scss
  packages/css-framework/package.json
  packages/css-framework/src/components/_alert.scss
  packages/css-framework/src/components/_drawer.scss
  packages/css-framework/src/fragments/_notification-panel.scss
  packages/docs-site/package.json
  packages/docs-site/src/library/images/components/alert/anatomy.svg
  packages/docs-site/src/library/images/components/alert/component.svg
  packages/docs-site/src/library/images/components/alert/states.svg
  packages/docs-site/src/library/images/components/card/anatomy.svg
  packages/docs-site/src/library/images/components/card/component.svg
  packages/docs-site/src/library/images/components/drawer/anatomy.svg
  packages/docs-site/src/library/images/components/drawer/component.svg
  packages/docs-site/src/library/images/components/range-slider/anatomy.svg
  packages/docs-site/src/library/images/components/range-slider/component.svg
  packages/docs-site/src/library/images/components/range-slider/states.svg
  packages/docs-site/src/library/images/components/range-slider/variations.svg
  packages/docs-site/src/library/pages/components/alert.md
  packages/docs-site/src/library/pages/components/card.md
  packages/docs-site/src/library/pages/components/drawer.md
  packages/docs-site/src/library/pages/components/range-slider.md
  packages/docs-site/src/library/pages/styles/colours.md
  packages/eslint-config-react/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Alert/Alert.stories.tsx
  packages/react-component-library/src/components/Alert/Alert.test.tsx
  packages/react-component-library/src/components/Alert/Alert.tsx
  packages/react-component-library/src/components/Alert/constants.ts
  packages/react-component-library/src/components/Alert/index.tsx
  packages/react-component-library/src/components/Drawer/Drawer.stories.tsx
  packages/react-component-library/src/components/Drawer/Drawer.test.tsx
  packages/react-component-library/src/components/Drawer/Drawer.tsx
  packages/react-component-library/src/components/Drawer/index.tsx
  packages/react-component-library/src/components/Searchbar/index.tsx
  packages/react-component-library/src/components/TabSet/README.md
  packages/react-component-library/src/components/TabSet/Tab.tsx
  packages/react-component-library/src/components/TabSet/TabContent.tsx
  packages/react-component-library/src/components/TabSet/TabItem.tsx
  packages/react-component-library/src/components/TabSet/TabSet.stories.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
  packages/react-component-library/src/components/TabSet/TabSet.tsx
  packages/react-component-library/src/components/TabSet/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/fragments/Masthead/Masthead.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.tsx
  packages/react-component-library/src/fragments/NotificationPanel/constants.ts
  packages/react-component-library/src/fragments/NotificationPanel/index.tsx
  packages/react-component-library/src/fragments/NotificationPanel/notificationPosition.test.ts
  packages/react-component-library/src/fragments/NotificationPanel/notificationPosition.ts
  packages/react-component-library/src/fragments/NotificationPanel/useNotificationPanel.ts
  packages/react-component-library/src/hooks/index.ts
  packages/react-component-library/src/hooks/useDocumentClick.ts
  packages/react-component-library/src/index.ts
  packages/reactapp/package.json
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: release

#451 Remove redundant legacy tsconfig file
  tsconfig.json
Labels: enhancement

#434 Popover Component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_popover.scss
  packages/css-framework/src/fragments/_notification-panel.scss
  packages/css-framework/src/objects/_floating-box.scss
  packages/docs-site/src/library/pages/components/popover.md
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Popover/Popover.stories.tsx
  packages/react-component-library/src/components/Popover/Popover.test.tsx
  packages/react-component-library/src/components/Popover/Popover.tsx
  packages/react-component-library/src/components/Popover/constants.ts
  packages/react-component-library/src/components/Popover/index.ts
  packages/react-component-library/src/components/Popover/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.tsx
  packages/react-component-library/src/fragments/NotificationPanel/constants.ts
  packages/react-component-library/src/fragments/NotificationPanel/notificationPosition.test.ts
  packages/react-component-library/src/fragments/NotificationPanel/notificationPosition.ts
  packages/react-component-library/src/index.ts
  packages/react-component-library/src/primitives/FloatingBox/FloatingBox.test.tsx
  packages/react-component-library/src/primitives/FloatingBox/FloatingBox.tsx
  packages/react-component-library/src/primitives/FloatingBox/constants.ts
  packages/react-component-library/src/primitives/FloatingBox/index.ts
  packages/react-component-library/src/primitives/index.ts
  yarn.lock
Labels: component, enhancement

#443 Add scrollable tab set
  packages/css-framework/src/components/_tab-set.scss
  packages/react-component-library/src/components/TabSet/ScrollButton.tsx
  packages/react-component-library/src/components/TabSet/Tab.tsx
  packages/react-component-library/src/components/TabSet/TabContent.tsx
  packages/react-component-library/src/components/TabSet/TabItem.tsx
  packages/react-component-library/src/components/TabSet/TabSet.stories.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
  packages/react-component-library/src/components/TabSet/TabSet.tsx
  packages/react-component-library/src/components/TabSet/constants.ts
  packages/react-component-library/src/components/TabSet/useScrollableTabSet.ts
Labels: component

#454 Update scrollable tab set docs
  packages/docs-site/src/library/pages/components/tab-set.md
Labels: Docs Site, component, documentation

#449 Add smooth scrolling to scrollable tab set
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
  packages/react-component-library/src/components/TabSet/TabSet.tsx
  packages/react-component-library/src/components/TabSet/useScrollableTabSet.ts
Labels: component, enhancement

#453 Update styles to be mobile first for scrollable tab set
  packages/css-framework/src/components/_tab-set.scss
Labels: component, enhancement

#457 Upgrade dependencies
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/eslint-config-react/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
  packages/reactapp/package.json
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: devops, security
