Repository Royal-Navy/design-system, pull requests merged in 2019-07, with the labels that each got.

#98 Refactor the TabSet implementation
  packages/react-component-library/src/components/TabSet/Tab.tsx
  packages/react-component-library/src/components/TabSet/TabSet.stories.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
  packages/react-component-library/src/components/TabSet/index.tsx
Labels: enhancement

#99 Feature/EN-695 update component template to include tab jsx
  packages/documentation/library/templates/components.md
  packages/react-component-library/src/index.ts
Labels: enhancement

#100 Feature/EN-697 Add usage examples to component template
  packages/documentation/library/templates/components.md
Labels: enhancement

#101 Some changes to the docs template to give structure
  packages/documentation/library/templates/components.md
Labels: enhancement

#103 Fix bug with sub nav sizing in docs site
  packages/docs-site/src/components/presenters/post-article/index.js
  packages/docs-site/src/components/presenters/post-article/post-article.scss
  packages/docs-site/src/components/presenters/sidebar/sidebar.scss
  packages/docs-site/src/templates/default.scss
Labels: bug

#95 Feature/EN-692 implement homepage mdx
  packages/docs-site/src/components/presenters/Masthead/index.js
  packages/docs-site/src/components/presenters/card/card.scss
  packages/docs-site/src/components/presenters/card/index.js
  packages/docs-site/src/components/presenters/hero-banner/index.js
  packages/docs-site/src/library/pages/index.md
Labels: enhancement

#105 Documentation for Button component
  packages/docs-site/src/library/pages/components/button.md
Labels: enhancement

#109 Update site structure to reflect latest sitemap
  packages/docs-site/src/library/pages/about/index.md
  packages/docs-site/src/library/pages/about/standards-roadmap.md
  packages/docs-site/src/library/pages/community/index.md
  packages/docs-site/src/library/pages/contact.md
  packages/docs-site/src/library/pages/get-started/design/index.md
  packages/docs-site/src/library/pages/get-started/prototyping/index.md
  packages/docs-site/src/library/pages/patterns/index.md
Labels: enhancement

#111 Add TabSet develop documentation
  packages/docs-site/src/library/pages/components/tab-set.md
Labels: enhancement

#121 Fix race condition causing types to be deleted during component build
  packages/react-component-library/package.json
  yarn.lock
Labels: bug

#123 Improve nav component
  packages/docs-site/src/library/pages/components/nav.md
  packages/react-component-library/src/components/Nav/Link.tsx
  packages/react-component-library/src/components/Nav/Nav.stories.tsx
  packages/react-component-library/src/components/Nav/NavItem.tsx
  packages/react-component-library/src/components/Nav/README.md
  packages/react-component-library/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/react-component-library/src/components/Nav/index.tsx
Labels: bug

#120 EN-663 Sidebar component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_avatar.scss
  packages/css-framework/src/components/_popover.scss
  packages/css-framework/src/fragments/_notification-side-panel.scss
  packages/css-framework/src/fragments/_sidebar.scss
  packages/docs-site/src/components/presenters/code-highlighter/index.js
  packages/docs-site/src/library/pages/components/sidebar.md
  packages/react-component-library/.storybook/config.ts
  packages/react-component-library/src/components/Avatar/index.tsx
  packages/react-component-library/src/components/Link/index.tsx
  packages/react-component-library/src/components/Popover/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/fragments/NotificationSidePanel/index.tsx
  packages/react-component-library/src/fragments/Sidebar/Sidebar.stories.tsx
  packages/react-component-library/src/fragments/Sidebar/index.tsx
  packages/react-component-library/src/fragments/index.ts
  packages/react-component-library/src/icons/Bell.tsx
  packages/react-component-library/src/icons/Graph.tsx
  packages/react-component-library/src/icons/House.tsx
  packages/react-component-library/src/icons/Tools.tsx
  packages/react-component-library/src/icons/index.ts
  packages/react-component-library/src/index.ts
  packages/react-component-library/src/types/ComponentWithClass.d.ts
  packages/react-component-library/src/types/Link.d.ts
  packages/react-component-library/src/types/NavItems.d.ts
Labels: enhancement

#125 EN-717 Fix display of component name in React Dev Tools
  packages/react-component-library/src/components/Avatar/index.tsx
  packages/react-component-library/src/components/Badge/index.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumb.tsx
  packages/react-component-library/src/components/Breadcrumbs/EndTitle.tsx
  packages/react-component-library/src/components/Breadcrumbs/index.tsx
  packages/react-component-library/src/components/Button/index.tsx
  packages/react-component-library/src/components/Link/index.tsx
  packages/react-component-library/src/components/Links/LinkItem.tsx
  packages/react-component-library/src/components/Links/index.tsx
  packages/react-component-library/src/components/Nav/Link.tsx
  packages/react-component-library/src/components/Nav/index.tsx
  packages/react-component-library/src/components/PhaseBanner/index.tsx
  packages/react-component-library/src/components/Popover/index.tsx
  packages/react-component-library/src/components/TabSet/Tab.tsx
  packages/react-component-library/src/components/TabSet/index.tsx
  packages/react-component-library/src/components/TextInput/index.tsx
  packages/react-component-library/src/fragments/NotificationSidePanel/index.tsx
  packages/react-component-library/src/fragments/Sidebar/index.tsx
  packages/react-component-library/src/icons/Bell.tsx
  packages/react-component-library/src/icons/Graph.tsx
  packages/react-component-library/src/icons/House.tsx
  packages/react-component-library/src/icons/Logo.tsx
  packages/react-component-library/src/icons/Search.tsx
  packages/react-component-library/src/icons/Tools.tsx
  packages/react-component-library/src/icons/TriangleDown.tsx
  packages/react-component-library/src/icons/TriangleUp.tsx
Labels: bug

#126 EN-718 Full width phase banner
  packages/css-framework/src/components/_phase-banner.scss
  packages/docs-site/src/library/pages/components/phase-banner.md
  packages/react-component-library/src/components/PhaseBanner/index.tsx
Labels: enhancement

#127 Fix some missing imports
  packages/css-framework/src/components/_pagination.scss
  packages/docs-site/src/library/pages/components/pagination.md
Labels: bug

#128 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#116 Feature/EN-679 getting started develop docs
  packages/docs-site/src/library/pages/get-started/design/index.md
  packages/docs-site/src/library/pages/get-started/development/index.md
  packages/docs-site/src/library/pages/get-started/development/installation.md
  packages/docs-site/src/library/pages/get-started/development/learning-resources.md
  packages/docs-site/src/library/pages/get-started/development/sass-css-framework.md
Labels: enhancement

#133 Update dependencies to address audit warning
  packages/docs-site/package.json
  yarn.lock
Labels: bug

#134 Tabbed Navigation
  packages/css-framework/index.scss
  packages/css-framework/src/components/_tab-nav.scss
  packages/docs-site/src/library/pages/components/nav.md
  packages/docs-site/src/library/pages/components/tab-nav.md
  packages/react-component-library/src/components/TabNav/TabNav.stories.tsx
  packages/react-component-library/src/components/TabNav/TabNav.test.tsx
  packages/react-component-library/src/components/TabNav/TabNavItem.tsx
  packages/react-component-library/src/components/TabNav/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: enhancement

#139 Bugfix/EN-724 fix namespacing for pagination component
  packages/css-framework/src/components/_pagination.scss
  packages/react-component-library/src/components/Pagination/index.tsx
Labels: bug

#138 Improve Popover
  packages/css-framework/src/components/_popover.scss
  packages/react-component-library/src/components/Popover/Popover.stories.tsx
  packages/react-component-library/src/components/Popover/index.tsx
  packages/react-component-library/src/fragments/NotificationSidePanel/index.tsx
Labels: enhancement

#140 Bugfix/EN-725 onChangeCallback invoked with incorrect page value
  packages/react-component-library/src/components/Pagination/Pagination.test.tsx
  packages/react-component-library/src/components/Pagination/usePageChange.tsx
Labels: bug

#141 Feature/EN-720 implement custom 404 page
  packages/docs-site/src/components/presenters/hero-banner/index.js
  packages/docs-site/src/pages/404.js
  packages/docs-site/src/pages/css/404.scss
Labels: enhancement

#144 Notification panel
  packages/css-framework/index.scss
  packages/css-framework/src/fragments/_notification-panel.scss
  packages/css-framework/src/fragments/_notification-side-panel.scss
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Popover/index.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/index.tsx
  packages/react-component-library/src/fragments/NotificationSidePanel/index.tsx
  packages/react-component-library/src/fragments/Sidebar/index.tsx
  packages/react-component-library/src/fragments/index.ts
  packages/react-component-library/src/index.ts
  packages/react-component-library/src/types/Position.d.ts
  yarn.lock
Labels: enhancement

#147 Update README.md
  README.md
Labels: enhancement

#152 Fix issue with sidebar position
  packages/css-framework/src/fragments/_sidebar.scss
Labels: bug

#153 Add support for additional className to Badge component
  packages/docs-site/src/library/pages/components/badge.md
  packages/react-component-library/src/components/Badge/index.tsx
Labels: enhancement

#155 Feature/EN-732 fix navigation issues
  packages/docs-site/src/components/presenters/Masthead/index.js
  packages/docs-site/src/components/presenters/Masthead/masthead.scss
  packages/docs-site/src/hooks/usePrimaryNavData.js
  packages/docs-site/src/hooks/usePrimaryNavData.test.js
  packages/docs-site/src/library/pages/about/standards-roadmap.md
  packages/docs-site/src/library/pages/components/dialog.md
  packages/docs-site/src/library/pages/components/progress.md
  packages/docs-site/src/library/pages/components/table.md
  packages/docs-site/src/library/pages/styles/breakpoints.md
  packages/docs-site/src/library/pages/styles/colours.md
  packages/docs-site/src/library/pages/styles/container.md
  packages/docs-site/src/library/pages/styles/spacing.md
  packages/docs-site/src/library/pages/styles/typography.md
  packages/docs-site/src/utils/nav.js
  packages/react-component-library/src/components/Nav/Nav.stories.tsx
  packages/react-component-library/src/components/Nav/Nav.test.tsx
  packages/react-component-library/src/components/Nav/NavItem.tsx
  packages/react-component-library/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/react-component-library/src/components/Nav/index.tsx
Labels: bug, enhancement

#157 Feature/various snagging fixes
  packages/docs-site/src/components/presenters/Masthead/index.js
  packages/docs-site/src/components/presenters/hero-banner/index.js
  packages/docs-site/src/library/pages/contact.md
  packages/docs-site/src/library/pages/index.md
Labels: bug

#156 Fixes to Badge spacing, Sidebar and make Breadcrumb consistent.
  packages/css-framework/src/components/_badge.scss
  packages/css-framework/src/fragments/_sidebar.scss
  packages/docs-site/src/library/pages/components/breadcrumbs.md
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumb.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  packages/react-component-library/src/components/Breadcrumbs/README.md
  packages/react-component-library/src/components/Breadcrumbs/index.tsx
  packages/react-component-library/src/components/Nav/Link.tsx
  packages/react-component-library/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/react-component-library/src/components/Nav/index.tsx
Labels: bug

#159 Bugfix/duplicate svg images for component pages
  packages/docs-site/src/components/presenters/hero-banner/hero-banner.scss
  packages/docs-site/src/library/images/components/breadcrumbs/anatomy.svg
  packages/docs-site/src/library/images/components/breadcrumbs/component.svg
  packages/docs-site/src/library/images/components/breadcrumbs/states.svg
  packages/docs-site/src/library/pages/components/badge.md
  packages/docs-site/src/library/pages/components/breadcrumbs.md
  packages/docs-site/src/library/pages/components/button.md
  packages/docs-site/src/library/pages/components/forms/input.md
  packages/docs-site/src/library/pages/components/nav.md
  packages/docs-site/src/library/pages/components/pagination.md
  packages/docs-site/src/library/pages/components/phase-banner.md
  packages/docs-site/src/library/pages/components/sidebar.md
  packages/docs-site/src/library/pages/components/tab-set.md
Labels: bug

#160 Fix broken import
  packages/docs-site/src/library/pages/components/forms/input.md
Labels: bug

#163 Feature/make entire card clickable
  packages/docs-site/src/components/presenters/card/card.scss
  packages/docs-site/src/components/presenters/card/index.js
  packages/docs-site/src/components/presenters/card/index.test.js
  packages/docs-site/src/components/presenters/post-article/post-article.scss
  packages/docs-site/src/library/pages/get-started/development/installation.md
Labels: bug, enhancement

#166 Minor content adjustments
  packages/docs-site/src/library/pages/get-started/design/index.md
  packages/docs-site/src/library/pages/get-started/development/index.md
  packages/docs-site/src/library/pages/get-started/development/installation.md
  packages/docs-site/src/library/pages/get-started/development/learning-resources.md
  packages/docs-site/src/library/pages/get-started/development/sass-css-framework.md
  packages/docs-site/src/library/pages/get-started/index.md
Labels: bug

#167 Bugfix/logo width
  packages/docs-site/src/components/presenters/Masthead/images/site-logo.svg
  packages/docs-site/src/components/presenters/Masthead/masthead.scss
Labels: bug

#170 Feature/update ci config for release
  .circleci/config.yml
  packages/css-framework/package.json
  packages/eslint-config-react/package.json
  packages/react-component-library/package.json
  packages/storybook-react-input-state/package.json
  packages/vue-component-library/package.json
Labels: devops

#173 Add publish job for eslint-config-react
  .circleci/config.yml
Labels: devops

#174 Fix missing Logo icon export
  packages/react-component-library/src/icons/index.ts
Labels: bug

#175 Minor correction for tab nav to remove margin causing issues
  packages/css-framework/src/components/_tab-nav.scss
Labels: bug

#176 Fix error in Notification panel when the user scrolls
  packages/react-component-library/src/fragments/NotificationPanel/index.tsx
Labels: bug

#177 Add datatype for user
  packages/react-component-library/src/fragments/Sidebar/index.tsx
  packages/react-component-library/src/types/User.d.ts
Labels: enhancement

#178 Add a dark variation for Avatar
  packages/css-framework/src/components/_avatar.scss
  packages/react-component-library/src/components/Avatar/index.tsx
Labels: enhancement

#184 1.0.1
  .circleci/config.yml
  package.json
  packages/css-framework/package.json
  packages/css-framework/src/components/_avatar.scss
  packages/css-framework/src/components/_layout.scss
  packages/css-framework/src/components/_tab-nav.scss
  packages/docs-site/package.json
  packages/docs-site/src/components/presenters/Masthead/masthead.scss
  packages/docs-site/src/components/presenters/card/card.scss
  packages/docs-site/src/components/presenters/hero-banner/hero-banner.scss
  packages/docs-site/src/components/presenters/layout/globals.scss
  packages/docs-site/src/components/presenters/layout/index.js
  packages/docs-site/src/library/pages/index.md
  packages/docs-site/src/templates/home.js
  packages/docs-site/src/templates/home.scss
  packages/eslint-config-react/package.json
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Avatar/index.tsx
  packages/react-component-library/src/fragments/NotificationPanel/index.tsx
  packages/react-component-library/src/fragments/Sidebar/index.tsx
  packages/react-component-library/src/icons/index.ts
  packages/react-component-library/src/types/User.d.ts
  packages/storybook-react-input-state/package.json
  packages/vue-component-library/package.json
Labels: bug
