Repository Royal-Navy/design-system, pull requests merged in 2019-10, with the labels that each got.

#290 Dialog & Modal Components
  packages/css-framework/src/components/_dialog.scss
  packages/css-framework/src/components/_modal.scss
  packages/docs-site/src/components/presenters/code-highlighter/code-highlighter.scss
  packages/docs-site/src/components/presenters/code-highlighter/index.js
  packages/docs-site/src/components/presenters/layout/globals.scss
  packages/docs-site/src/library/images/components/dialog/anatomy.svg
  packages/docs-site/src/library/images/components/dialog/component.svg
  packages/docs-site/src/library/images/components/modal/anatomy.svg
  packages/docs-site/src/library/images/components/modal/component.svg
  packages/docs-site/src/library/images/components/modal/usage.svg
  packages/docs-site/src/library/pages/components/dialog.md
  packages/docs-site/src/library/pages/components/modal.md
  packages/icon-library/src/assets/arrows/button-confirm.svg
  packages/react-component-library/src/components/Button/Button.tsx
  packages/react-component-library/src/components/Dialog/Dialog.stories.tsx
  packages/react-component-library/src/components/Dialog/Dialog.test.tsx
  packages/react-component-library/src/components/Dialog/Dialog.tsx
  packages/react-component-library/src/components/Dialog/index.tsx
  packages/react-component-library/src/components/Modal/Footer.tsx
  packages/react-component-library/src/components/Modal/Header.tsx
  packages/react-component-library/src/components/Modal/Modal.stories.tsx
  packages/react-component-library/src/components/Modal/Modal.test.tsx
  packages/react-component-library/src/components/Modal/Modal.tsx
  packages/react-component-library/src/components/Modal/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
  yarn.lock
Labels: component, documentation, enhancement

#313 Hotfix/ci running wrong build type
  .circleci/config.yml
Labels: bug

#311 Forms documentation
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/components/form/checkbox.md
  packages/docs-site/src/library/pages/components/form/index.md
  packages/docs-site/src/library/pages/components/form/input.md
  packages/docs-site/src/library/pages/components/form/number-input.md
  packages/docs-site/src/library/pages/components/form/radio.md
  packages/docs-site/src/library/pages/components/form/select.md
  packages/docs-site/src/library/pages/forms.md
Labels: enhancement

#319 Docs Content Update
  packages/docs-site/src/library/images/components/button/primary-hierarchy.svg
  packages/docs-site/src/library/images/components/button/tertiary-hierarchy.svg
  packages/docs-site/src/library/pages/about/index.md
  packages/docs-site/src/library/pages/components/badge.md
  packages/docs-site/src/library/pages/components/breadcrumbs.md
  packages/docs-site/src/library/pages/components/button.md
  packages/docs-site/src/library/pages/components/dialog.md
  packages/docs-site/src/library/pages/components/dropdown.md
  packages/docs-site/src/library/pages/components/form/checkbox.md
  packages/docs-site/src/library/pages/components/form/index.md
  packages/docs-site/src/library/pages/components/form/input.md
  packages/docs-site/src/library/pages/components/form/number-input.md
  packages/docs-site/src/library/pages/components/form/radio.md
  packages/docs-site/src/library/pages/components/form/select.md
  packages/docs-site/src/library/pages/components/index.md
  packages/docs-site/src/library/pages/components/masthead.md
  packages/docs-site/src/library/pages/components/modal.md
  packages/docs-site/src/library/pages/components/nav.md
  packages/docs-site/src/library/pages/components/pagination.md
  packages/docs-site/src/library/pages/components/phase-banner.md
  packages/docs-site/src/library/pages/components/sidebar.md
  packages/docs-site/src/library/pages/components/switch.md
  packages/docs-site/src/library/pages/components/tab-set.md
  packages/docs-site/src/library/pages/contact.md
  packages/docs-site/src/library/pages/forms.md
  packages/docs-site/src/library/pages/get-started/design/index.md
  packages/docs-site/src/library/pages/get-started/development/index.md
  packages/docs-site/src/library/pages/get-started/development/installation.md
  packages/docs-site/src/library/pages/get-started/development/learning-resources.md
  packages/docs-site/src/library/pages/get-started/development/sass-css-framework.md
  packages/docs-site/src/library/pages/get-started/index.md
  packages/docs-site/src/library/pages/index.md
  packages/docs-site/src/library/pages/styles/breakpoints.md
  packages/docs-site/src/library/pages/styles/colours.md
  packages/docs-site/src/library/pages/styles/container.md
  packages/docs-site/src/library/pages/styles/dividers.md
  packages/docs-site/src/library/pages/styles/index.md
  packages/docs-site/src/library/pages/styles/spacing.md
  packages/docs-site/src/library/pages/styles/typography.md
  packages/docs-site/src/templates/home.js
Labels: Docs Site, documentation

#328 Tooltip component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_tooltip.scss
  packages/docs-site/src/library/images/components/tooltip/anatomy.svg
  packages/docs-site/src/library/images/components/tooltip/component.svg
  packages/docs-site/src/library/images/components/tooltip/states.svg
  packages/docs-site/src/library/images/components/tooltip/variations.svg
  packages/docs-site/src/library/pages/components/tooltip.md
  packages/react-component-library/src/components/Tooltip/Tooltip.stories.tsx
  packages/react-component-library/src/components/Tooltip/Tooltip.test.tsx
  packages/react-component-library/src/components/Tooltip/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component

#356 Fix minor typo in storybook docs for Phasebanner
  packages/docs-site/src/library/pages/components/phase-banner.md
Labels: bug

#355 Fix lint hook
  package.json
  packages/eslint-config-react/package.json
  packages/react-component-library/package.json
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: bug, devops

#357 Remove underline when hovering over Masthead navigation
  packages/css-framework/src/components/_scrollable-nav.scss
Labels: bug

#359 SCSS Rename Helper to Utility
  packages/css-framework/README.md
  packages/css-framework/index.scss
  packages/css-framework/src/_config.scss
  packages/css-framework/src/utilities/_clearfix.scss
  packages/css-framework/src/utilities/_flex.scss
  packages/css-framework/src/utilities/_position.scss
  packages/css-framework/src/utilities/_shadows.scss
  packages/css-framework/src/utilities/_sizing.scss
  packages/css-framework/src/utilities/_spacing.scss
  packages/css-framework/src/utilities/_typography.scss
  packages/css-framework/src/utilities/_visibility.scss
  packages/docs-site/src/library/pages/get-started/development/sass-css-framework.md
  packages/docs-site/src/library/pages/index.md
  packages/docs-site/src/library/pages/styles/breakpoints.md
  packages/docs-site/src/library/pages/styles/dividers.md
  packages/docs-site/src/library/pages/styles/spacing.md
  packages/docs-site/src/library/pages/styles/typography.md
Labels: v2

#265 Avatar Component
  packages/css-framework/src/components/_avatar.scss
  packages/docs-site/src/library/images/components/avatar/anatomy.svg
  packages/docs-site/src/library/images/components/avatar/component.svg
  packages/docs-site/src/library/images/components/avatar/states.svg
  packages/docs-site/src/library/pages/components/avatar.md
  packages/react-component-library/src/components/Avatar/Avatar.stories.tsx
  packages/react-component-library/src/components/Avatar/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: Design - Signed Off, component, documentation

#365 Fix Textinput state
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/components/form/input.md
  packages/react-component-library/package.json
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/types/StorybookReactInputState.d.ts
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: bug

#354 Add basic table component
  packages/css-framework/src/components/_table.scss
  packages/docs-site/src/library/images/components/table/anatomy.svg
  packages/docs-site/src/library/images/components/table/component.svg
  packages/docs-site/src/library/pages/components/table.md
  packages/react-component-library/src/components/Table/Column.tsx
  packages/react-component-library/src/components/Table/Table.stories.tsx
  packages/react-component-library/src/components/Table/Table.test.tsx
  packages/react-component-library/src/components/Table/Table.tsx
  packages/react-component-library/src/components/Table/index.tsx
  packages/react-component-library/src/index.ts
Labels: component, documentation

#383 Path Machine in the middle vulnerability
  package.json
  packages/react-component-library/package.json
  yarn.lock
Labels: security

#380 Fix SVG styles in doc site
  packages/css-framework/src/components/_tab-set.scss
  packages/docs-site/src/components/presenters/post-article/post-article.scss
Labels: bug

#382 Bugfix/textinput docs
  packages/docs-site/src/library/pages/components/form/index.md
  packages/docs-site/src/library/pages/components/form/input.md
Labels: bug, documentation

#381 Textarea React Component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_textarea.scss
  packages/docs-site/src/library/images/components/forms/textarea/anatomy.svg
  packages/docs-site/src/library/images/components/forms/textarea/component.svg
  packages/docs-site/src/library/images/components/forms/textarea/states.svg
  packages/docs-site/src/library/images/components/forms/textarea/variations.svg
  packages/docs-site/src/library/pages/components/form/textarea.md
  packages/react-component-library/src/components/Formik.ts
  packages/react-component-library/src/components/TextArea/TextArea.stories.tsx
  packages/react-component-library/src/components/TextArea/TextArea.test.tsx
  packages/react-component-library/src/components/TextArea/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, enhancement

#367 Update table component to demonstrate arbitrary cell content
  packages/docs-site/src/library/pages/components/table.md
  packages/react-component-library/src/components/Table/Table.stories.tsx
  packages/react-component-library/src/components/Table/Table.test.tsx
Labels: documentation, enhancement

#384 Update dependencies
  package.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/docs-site/src/components/presenters/footer/index.js
  packages/eslint-config-react/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
  packages/reactapp/package.json
  packages/storybook-react-input-state/package.json
  yarn.lock
Labels: devops

#395 Bugfix/get tree shaking working
  packages/icon-library/.babelrc
  packages/icon-library/generate-exports.sh
  packages/icon-library/package.json
  packages/icon-library/webpack/prod.js
Labels: bug

#397 Release/1.6.1
  lerna.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/eslint-config-react/package.json
  packages/icon-library/.babelrc
  packages/icon-library/generate-exports.sh
  packages/icon-library/package.json
  packages/icon-library/webpack/prod.js
  packages/react-component-library/package.json
  packages/reactapp/package.json
  packages/storybook-react-input-state/package.json
Labels: release

#401 Add support for disabled buttons
  packages/css-framework/src/components/_button.scss
  packages/docs-site/src/library/pages/components/button.md
  packages/react-component-library/src/components/Button/Button.tsx
Labels: Atom, component, enhancement
