Repository Royal-Navy/design-system, pull requests merged in 2019-05, with the labels that each got.

#10 EN-293 Feature/vue component transfer
  packages/css-framework/index.scss
  packages/css-framework/src/components/_transfer.scss
  packages/documentation/library/pages/develop/components/images/transfer.gif
  packages/documentation/library/pages/develop/components/transfer.md
  packages/vue-component-library/package.json
  packages/vue-component-library/src/components/RnTransfer/RnTransfer.spec.js
  packages/vue-component-library/src/components/RnTransfer/RnTransfer.stories.js
  packages/vue-component-library/src/components/RnTransfer/__snapshots__/RnTransfer.spec.js.snap
  packages/vue-component-library/src/components/RnTransfer/arrows.svg
  packages/vue-component-library/src/components/RnTransfer/index.vue
  packages/vue-component-library/src/components/RnTransfer/scripts.js
  yarn.lock
Labels: enhancement

#12 Allow Toggle to work in HTML page
  package.json
  packages/html-component-library/.gitignore
  packages/html-component-library/README.md
  packages/html-component-library/package.json
  packages/html-component-library/public/index.html
  packages/html-component-library/src/index.js
  packages/html-component-library/webpack.config.js
  packages/vue-component-library/src/components/RnToggle/RnToggle.spec.js
  packages/vue-component-library/src/components/index.ts
  yarn.lock
Labels: enhancement

#13 Add support for links to Vue Dropdown
  packages/css-framework/src/components/_dropdown.scss
  packages/documentation/library/pages/develop/components/dropdowns.md
  packages/documentation/library/pages/develop/components/images/drop1.png
  packages/documentation/library/pages/develop/components/images/drop2.png
  packages/html-component-library/public/index.html
  packages/html-component-library/src/index.js
  packages/vue-component-library/src/components/RnDropdown/RnDropdown.spec.js
  packages/vue-component-library/src/components/RnDropdown/RnDropdown.stories.js
  packages/vue-component-library/src/components/RnDropdown/index.vue
  packages/vue-component-library/src/components/RnDropdown/scripts.js
Labels: enhancement

#14 Added documentation for Tooltip
  packages/documentation/library/pages/develop/components/tootips.md
Labels: enhancement

#18 EN-590 Fix node-sass security alert and move to dart sass
  packages/css-framework/package.json
  packages/html-storybook/.storybook/webpack.config.js
  packages/html-storybook/package.json
  packages/react-component-library/.storybook/webpack.config.js
  packages/react-component-library/package.json
  packages/vue-component-library/.storybook/webpack.config.js
  packages/vue-component-library/package.json
  yarn.lock
Labels: bug

#19 Docsite deployment automation (Prod & Staging)
  .circleci/config.yml
  packages/docs-site/.firebaserc
Labels: Devops

#21 Update nvm config to use 10.15.3, current LTS
  .nvmrc
Labels: Devops

#24 EN-598 Update colour palette
  packages/css-framework/index.scss
  packages/css-framework/package.json
  packages/css-framework/src/components/_alert.scss
  packages/css-framework/src/components/_button.scss
  packages/css-framework/src/components/_card.scss
  packages/css-framework/src/components/_nav.scss
  packages/css-framework/src/components/_toggle.scss
  packages/css-framework/src/components/_transfer.scss
  packages/css-framework/src/contexts/_light.scss
Labels: enhancement

#15 EN-299 Sortable table
  packages/css-framework/src/components/_table.scss
  packages/documentation/legacy/pages/develop/components/tables.md
  packages/vue-component-library/src/components/RnTable/RnTable.stories.js
  packages/vue-component-library/src/components/RnTable/__snapshots__/RnTable.spec.js.snap
  packages/vue-component-library/src/components/RnTable/index.vue
  packages/vue-component-library/src/components/RnTable/scripts.js
Labels: enhancement

#28 Storybook bug
  packages/html-storybook/.storybook/config.js
  packages/html-storybook/package.json
  packages/react-component-library/.storybook/config.js
  packages/react-component-library/package.json
  packages/storybook-react-input-state/package.json
  packages/vue-component-library/.storybook/webpack.config.js
  packages/vue-component-library/package.json
  yarn.lock
Labels: bug

#26 Docs consolidation
  packages/docs-site/.gitignore
  packages/docs-site/README.md
  packages/docs-site/docs-consolidator.js
  packages/docs-site/package.json
  packages/documentation/library/pages/components/alert.md
  packages/documentation/library/pages/components/avatar.md
  packages/documentation/library/pages/components/badge.md
  packages/documentation/library/pages/components/button.md
  packages/documentation/library/pages/components/card.md
  packages/documentation/library/pages/components/dialog.md
  packages/documentation/library/pages/components/dropdown.md
  packages/documentation/library/pages/components/icon.md
  packages/documentation/library/pages/components/input.md
  packages/documentation/library/pages/components/list.md
  packages/documentation/library/pages/components/modal.md
  packages/documentation/library/pages/components/nav.md
  packages/documentation/library/pages/components/progress.md
  packages/documentation/library/pages/components/table.md
  packages/documentation/library/pages/components/toggle.md
  packages/documentation/library/pages/components/transfer.md
  packages/vue-component-library/src/components/RnAlert/README.md
  packages/vue-component-library/src/components/RnAvatar/README.md
  packages/vue-component-library/src/components/RnBadge/README.md
  packages/vue-component-library/src/components/RnButton/README.md
  packages/vue-component-library/src/components/RnCard/README.md
  packages/vue-component-library/src/components/RnDialog/README.md
  packages/vue-component-library/src/components/RnDropdown/README.md
  packages/vue-component-library/src/components/RnDropdown/images/drop1.png
  packages/vue-component-library/src/components/RnDropdown/images/drop2.png
  packages/vue-component-library/src/components/RnIcon/README.md
  packages/vue-component-library/src/components/RnInput/README.md
  packages/vue-component-library/src/components/RnList/README.md
  packages/vue-component-library/src/components/RnModal/README.md
  packages/vue-component-library/src/components/RnNav/README.md
  packages/vue-component-library/src/components/RnProgress/README.md
  packages/vue-component-library/src/components/RnTable/README.md
  packages/vue-component-library/src/components/RnToggle/README.md
  packages/vue-component-library/src/components/RnToggle/images/toggle.png
  packages/vue-component-library/src/components/RnTransfer/README.md
  packages/vue-component-library/src/components/RnTransfer/arrows.svg
  packages/vue-component-library/src/components/RnTransfer/images/transfer.gif
  yarn.lock
Labels: enhancement

#29 EN-599 Buttons
  packages/css-framework/.stylelintrc
  packages/css-framework/index.scss
  packages/css-framework/src/abstracts/functions/map-get-default.scss
  packages/css-framework/src/components/_button.scss
  packages/react-component-library/src/components/Button/Button.stories.js
  packages/react-component-library/src/components/Button/Button.test.js
  packages/react-component-library/src/components/Button/README.md
  packages/react-component-library/src/components/Button/images/button-icon.png
  packages/react-component-library/src/components/Button/images/button-size.png
  packages/react-component-library/src/components/Button/images/button-variants.png
  packages/react-component-library/src/components/Button/index.js
Labels: enhancement

#31 EN-591 Navigation/Primary navigation
  packages/css-framework/src/components/_nav.scss
  packages/react-component-library/.storybook/config.js
  packages/react-component-library/.storybook/styles.css
  packages/react-component-library/src/components/Nav/Link.js
  packages/react-component-library/src/components/Nav/Nav.stories.js
  packages/react-component-library/src/components/Nav/NavItem.js
  packages/react-component-library/src/components/Nav/README.md
  packages/react-component-library/src/components/Nav/images/nav-horizontal.png
  packages/react-component-library/src/components/Nav/images/nav-sizes.png
  packages/react-component-library/src/components/Nav/images/nav-vertical.png
  packages/react-component-library/src/components/Nav/index.js
Labels: enhancement

#32 Add a thank you to BrowserStack for providing free browser testing.
  README.md
  images/Browserstack-logo.svg
Labels: Devops

#30 EN-592: React component phase banner
  packages/css-framework/index.scss
  packages/css-framework/src/components/_badge.scss
  packages/css-framework/src/components/_phase-banner.scss
  packages/css-framework/src/objects/_wrapper.scss
  packages/documentation/library/pages/components/phase-banner.md
  packages/react-component-library/src/components/PhaseBanner/PhaseBanner.stories.js
  packages/react-component-library/src/components/PhaseBanner/PhaseBanner.test.js
  packages/react-component-library/src/components/PhaseBanner/README.md
  packages/react-component-library/src/components/PhaseBanner/__snapshots__/PhaseBanner.test.js.snap
  packages/react-component-library/src/components/PhaseBanner/images/phase-banner-example.gif
  packages/react-component-library/src/components/PhaseBanner/index.js
Labels: enhancement

#27 Feature/add nesting and index sidebar
  packages/docs-site/gatsby-config.js
  packages/docs-site/package.json
  packages/docs-site/src/components/enhancers/withNavigation.js
  packages/docs-site/src/components/presenters/content-box/__snapshots__/index.test.js.snap
  packages/docs-site/src/components/presenters/content-box/content-box.scss
  packages/docs-site/src/components/presenters/content-box/index.js
  packages/docs-site/src/components/presenters/content-box/index.test.js
  packages/docs-site/src/components/presenters/layout/globals.scss
  packages/docs-site/src/components/presenters/layout/index.js
  packages/docs-site/src/components/presenters/post-article/index.js
  packages/docs-site/src/components/presenters/post-article/index.test.js
  packages/docs-site/src/components/presenters/post-article/post-article.scss
  packages/docs-site/src/components/presenters/post-article/post-md.scss
  packages/docs-site/src/components/presenters/seo/index.js
  packages/docs-site/src/components/presenters/sidebar/__snapshots__/index.test.js.snap
  packages/docs-site/src/components/presenters/sidebar/index.js
  packages/docs-site/src/components/presenters/sidebar/index.test.js
  packages/docs-site/src/components/presenters/sidebar/sidebar.scss
  packages/docs-site/src/components/sidebar/index.js
  packages/docs-site/src/pages/404.js
  packages/docs-site/src/templates/default.js
  packages/documentation/library/pages/about-the-design-system/index.md
  packages/documentation/library/pages/community/index.md
  packages/documentation/library/pages/components/index.md
  packages/documentation/library/pages/get-started/index.md
  packages/documentation/library/pages/index.md
  packages/documentation/library/pages/nelson-api-documentation/index.md
  packages/documentation/library/pages/patterns/index.md
  packages/documentation/library/pages/styles/index.md
Labels: enhancement

#34 Add support for SVG to React component library
  packages/react-component-library/package.json
  packages/react-component-library/src/types/svg.d.ts
  packages/react-component-library/webpack/common.js
  yarn.lock
Labels: enhancement

#38 Fix a couple of minor mistakes in Nav component
  packages/react-component-library/src/components/Nav/NavItem.tsx
  packages/react-component-library/src/components/Nav/README.md
Labels: bug

#36 Update React Component supported browsers to allow Chrome 38 testing
  packages/react-component-library/package.json
Labels: Devops

#37 Update .gitignore to make sure no build files are committed.
  .gitignore
Labels: bug

#35 EN-614: Docs consolidatior enhancement
  packages/docs-site/README.md
  packages/docs-site/docs-consolidator.js
  packages/docs-site/src/components/containers/.gitkeep
  packages/docs-site/src/components/enhancers/withNavigation.js
  packages/documentation/library/pages/components/forms/dropdown.md
  packages/documentation/library/pages/components/forms/index.md
  packages/documentation/library/pages/components/forms/input.md
  packages/documentation/library/pages/components/forms/toggle.md
  packages/documentation/library/pages/components/forms/transfer.md
  packages/react-component-library/.gitignore
Labels: enhancement

#39 EN-603 Links component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_links.scss
  packages/react-component-library/src/components/CustomLink/index.tsx
  packages/react-component-library/src/components/Links/Link.tsx
  packages/react-component-library/src/components/Links/LinkItem.tsx
  packages/react-component-library/src/components/Links/Links.stories.tsx
  packages/react-component-library/src/components/Links/README.md
  packages/react-component-library/src/components/Links/images/links.png
  packages/react-component-library/src/components/Links/index.tsx
  packages/react-component-library/src/components/Nav/Nav.stories.tsx
  packages/react-component-library/src/index.ts
Labels: enhancement

#45 Exclude tests from Code Climate checks
  .codeclimate.yml
Labels: enhancement

#44 Feature/nested navigation
  .codeclimate.yml
  packages/css-framework/src/components/_nav.scss
  packages/react-component-library/jest/__mocks__/uuid.js
  packages/react-component-library/src/components/Nav/Nav.stories.tsx
  packages/react-component-library/src/components/Nav/Nav.test.tsx
  packages/react-component-library/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/react-component-library/src/components/Nav/index.tsx
Labels: enhancement

#48 Update React test tool and cleanup jest config a little
  packages/docs-site/jest.config.js
  packages/docs-site/jest/__mocks__/fileMock.js
  packages/docs-site/jest/__mocks__/gatsby.js
  packages/docs-site/jest/preprocess.js
  packages/docs-site/jest/setupTests.js
  packages/docs-site/loadershim.js
  packages/docs-site/package.json
  packages/docs-site/setup-test-env.js
  yarn.lock
Labels: enhancement

#43 EN-593 - Hero banner
  packages/css-framework/src/components/_button.scss
  packages/docs-site/package.json
  packages/docs-site/src/components/presenters/hero-banner/hero-banner.scss
  packages/docs-site/src/components/presenters/hero-banner/index.js
  packages/docs-site/src/components/presenters/hero-banner/index.test.js
  yarn.lock
Labels: enhancement

#50 Feature/name in sketch toolkit widget
  packages/docs-site/src/components/presenters/sketch-widget/download-icon.svg
  packages/docs-site/src/components/presenters/sketch-widget/index.js
  packages/docs-site/src/components/presenters/sketch-widget/index.test.js
  packages/docs-site/src/components/presenters/sketch-widget/sketch-logo.svg
  packages/docs-site/src/components/presenters/sketch-widget/sketch-widget.scss
Labels: enhancement

#49 EN-603 footer
  packages/docs-site/src/components/presenters/footer/footer.scss
  packages/docs-site/src/components/presenters/footer/images/footer.png
  packages/docs-site/src/components/presenters/footer/index.js
  packages/docs-site/src/components/presenters/footer/index.test.js
  packages/docs-site/src/components/presenters/footer/logo.svg
  packages/docs-site/src/templates/default.js
Labels: enhancement
