Repository Royal-Navy/design-system, pull requests merged in 2019-09, with the labels that each got.

#249 Feature/sidebar enhancements
  packages/docs-site/src/components/presenters/sidebar/Link.js
  packages/docs-site/src/components/presenters/sidebar/index.js
  packages/docs-site/src/components/presenters/sidebar/sidebar.scss
  packages/docs-site/src/hooks/useSecondaryNavData.js
  packages/docs-site/src/hooks/useSecondaryNavData.test.js
  packages/docs-site/src/templates/default.js
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Nav/NavItem.tsx
  packages/react-component-library/src/components/Nav/__snapshots__/Nav.test.tsx.snap
  packages/react-component-library/src/components/Nav/index.tsx
  yarn.lock
Labels: enhancement

#240 Feature/masthead #187
  packages/css-framework/index.scss
  packages/css-framework/src/components/_popover.scss
  packages/css-framework/src/components/_scrollable-nav.scss
  packages/css-framework/src/components/_searchbar.scss
  packages/css-framework/src/fragments/_masthead.scss
  packages/css-framework/src/fragments/_notification-panel.scss
  packages/docs-site/src/library/images/components/masthead/anatomy.svg
  packages/docs-site/src/library/images/components/masthead/component.svg
  packages/docs-site/src/library/images/components/masthead/states.svg
  packages/docs-site/src/library/pages/components/masthead.md
  packages/react-component-library/jest/setupTests.ts
  packages/react-component-library/package.json
  packages/react-component-library/src/components/ScrollableNav/ScrollableNav.tsx
  packages/react-component-library/src/components/ScrollableNav/ScrollableNavItem.tsx
  packages/react-component-library/src/components/ScrollableNav/index.tsx
  packages/react-component-library/src/components/Searchbar/Searchbar.test.tsx
  packages/react-component-library/src/components/Searchbar/index.tsx
  packages/react-component-library/src/components/TextInput/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/fragments/Masthead/Masthead.stories.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.test.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.tsx
  packages/react-component-library/src/fragments/Masthead/UserLink.tsx
  packages/react-component-library/src/fragments/Masthead/index.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/index.tsx
  packages/react-component-library/src/fragments/index.ts
  packages/react-component-library/src/icons/Logo.tsx
  packages/react-component-library/src/icons/Right-Arrow.tsx
  packages/react-component-library/src/icons/Search.tsx
  packages/react-component-library/src/icons/index.ts
  packages/react-component-library/src/index.ts
  packages/react-component-library/src/types/reactIndianaDragScroll.d.ts
  yarn.lock
Labels: enhancement

#259 Fixing spelling mistake on Masthead States diagram
  packages/docs-site/src/library/images/components/masthead/states.svg
Labels: Docs Site, bug

#262 Update dependencies
  packages/css-framework/package.json
  packages/docs-site/.eslintrc.js
  packages/docs-site/gatsby-config.js
  packages/docs-site/jest/setupTests.js
  packages/docs-site/package.json
  packages/docs-site/src/components/presenters/post-article/index.js
  packages/docs-site/src/templates/default.js
  packages/docs-site/src/templates/home.js
  packages/eslint-config-react/index.js
  packages/react-component-library/.eslintrc.js
  packages/react-component-library/jest.config.js
  packages/react-component-library/jest/setupAfterEnv.ts
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  packages/react-component-library/src/components/Checkbox/Checkbox.test.tsx
  packages/react-component-library/src/components/Pagination/usePageChange.tsx
  packages/react-component-library/src/components/PhaseBanner/index.tsx
  packages/react-component-library/src/components/Radio/Radio.test.tsx
  packages/react-component-library/src/components/Searchbar/Searchbar.test.tsx
  packages/react-component-library/src/components/TabNav/TabNav.test.tsx
  packages/react-component-library/src/components/TextInput/TextInput.test.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/storybook-react-input-state/package.json
  packages/storybook-react-input-state/src/State.js
  yarn.lock
Labels: devops

#272 Select component
  package.json
  packages/css-framework/index.scss
  packages/css-framework/src/components/_select.scss
  packages/docs-site/src/library/images/components/forms/select/anatomy.svg
  packages/docs-site/src/library/images/components/forms/select/component.svg
  packages/docs-site/src/library/images/components/forms/select/states.svg
  packages/docs-site/src/library/pages/components/forms/select.md
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Badge/index.tsx
  packages/react-component-library/src/components/Select/DropdownIndicator.tsx
  packages/react-component-library/src/components/Select/Input.test.tsx
  packages/react-component-library/src/components/Select/Input.tsx
  packages/react-component-library/src/components/Select/Option.test.tsx
  packages/react-component-library/src/components/Select/Option.tsx
  packages/react-component-library/src/components/Select/Select.stories.tsx
  packages/react-component-library/src/components/Select/Select.tsx
  packages/react-component-library/src/components/Select/SingleValue.test.tsx
  packages/react-component-library/src/components/Select/SingleValue.tsx
  packages/react-component-library/src/components/Select/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/enhancers/index.tsx
  packages/react-component-library/src/icons/TriangleDown.tsx
  packages/react-component-library/src/icons/TriangleUp.tsx
  packages/react-component-library/src/index.ts
  packages/reactapp/.gitignore
  packages/reactapp/README.md
  packages/reactapp/package.json
  packages/reactapp/public/favicon.ico
  packages/reactapp/public/index.html
  packages/reactapp/public/logo192.png
  packages/reactapp/public/logo512.png
  packages/reactapp/public/manifest.json
  packages/reactapp/public/robots.txt
  packages/reactapp/src/App.js
  packages/reactapp/src/Basic.js
  packages/reactapp/src/index.js
  yarn.lock
Labels: component, enhancement

#266 Feature/switch component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_switch.scss
  packages/docs-site/src/library/images/components/switch/anatomy.svg
  packages/docs-site/src/library/images/components/switch/component.svg
  packages/docs-site/src/library/images/components/switch/states.svg
  packages/docs-site/src/library/pages/components/switch.md
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Formik.ts
  packages/react-component-library/src/components/Switch/Switch.stories.tsx
  packages/react-component-library/src/components/Switch/Switch.test.tsx
  packages/react-component-library/src/components/Switch/Switch.tsx
  packages/react-component-library/src/components/Switch/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
  packages/react-component-library/src/types/Switch.d.ts
  yarn.lock
Labels: component, enhancement

#283 Bug/icon dependency
  package.json
  packages/icon-library/package.json
Labels: bug

#281 Fix bug in Docs site cache clearance
  packages/docs-site/package.json
Labels: bug

#282 Fix sizing in Select component
  packages/css-framework/src/components/_select.scss
Labels: bug

#284 Fix cross dependency build issues
  .circleci/config.yml
Labels: bug

#291 Bugfix/Enable tree shaking
  packages/icon-library/.babelrc
  packages/icon-library/package.json
  packages/react-component-library/.babelrc
  packages/react-component-library/package.json
  yarn.lock
Labels: bug

#294 Update lock file to fix security vulnerability
  yarn.lock
Labels: devops

#293 Fix bug in withFormik not passing through classes
  packages/react-component-library/src/enhancers/withFormik.tsx
Labels: bug

#297 Bugfix/fix button issues
  packages/css-framework/src/components/_button.scss
  packages/react-component-library/src/components/Button/Button.stories.tsx
  packages/react-component-library/src/components/Button/Button.test.tsx
  packages/react-component-library/src/components/Button/Button.tsx
  packages/react-component-library/src/components/Button/index.tsx
  packages/react-component-library/src/components/Nav/Nav.stories.tsx
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: bug, component

#295 Number Input
  packages/css-framework/index.scss
  packages/css-framework/src/components/_numberinput.scss
  packages/docs-site/src/library/images/components/forms/number-clicker/anatomy.svg
  packages/docs-site/src/library/images/components/forms/number-clicker/button-states.svg
  packages/docs-site/src/library/images/components/forms/number-clicker/component.svg
  packages/docs-site/src/library/images/components/forms/number-clicker/states.svg
  packages/docs-site/src/library/pages/components/forms/input.md
  packages/docs-site/src/library/pages/components/forms/number-input.md
  packages/react-component-library/src/components/Formik.ts
  packages/react-component-library/src/components/NumberInput/NumberInput.stories.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.test.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.tsx
  packages/react-component-library/src/components/NumberInput/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
  packages/reactapp/src/App.js
  packages/reactapp/src/Basic.js
  packages/reactapp/src/NumberForm.js
Labels: component, enhancement
