Repository Royal-Navy/design-system, pull requests merged in 2020-02, with the labels that each got.

#609 Change overflow on table wrapper
  packages/css-framework/src/components/_table.scss
Labels: bug, component

#610 Adjust margin for Select component
  packages/css-framework/src/components/_select.scss
Labels: bug, component

#617 Fix working directory before publishing
  .circleci/config.yml
Labels: bug, devops

#618 Add explicit width and height
  packages/icon-library/src/assets/arrows/button-confirm.svg
Labels: bug, component

#627 Remove use of `react-addons-css-transition-group` in favour of `react-transition-group`
  package.json
  packages/css-framework/src/components/_searchbar.scss
  packages/css-framework/src/fragments/_notification-panel.scss
  packages/react-component-library/package.json
  packages/react-component-library/src/fragments/Masthead/Masthead.tsx
  packages/react-component-library/src/fragments/Masthead/useMastheadSearch.ts
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.tsx
  yarn.lock
Labels: devops

#631 Add ability to hide label for NumberInput
  packages/css-framework/src/components/_numberinput.scss
  packages/react-component-library/src/components/NumberInput/EndAdornment.tsx
  packages/react-component-library/src/components/NumberInput/EndAdornmentButton.tsx
  packages/react-component-library/src/components/NumberInput/Footnote.tsx
  packages/react-component-library/src/components/NumberInput/Input.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.stories.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.tsx
  packages/react-component-library/src/components/NumberInput/StartAdornment.tsx
  packages/react-component-library/src/components/NumberInput/constants.ts
  packages/react-component-library/src/components/NumberInput/useFocus.ts
Labels: component, enhancement

#641 Remove unnecessary testing of tag
  packages/react-component-library/src/components/CardFrame/CardFrame.test.tsx
  packages/react-component-library/src/components/Panel/Panel.test.tsx
  packages/react-component-library/src/components/Table/Table.test.tsx
Labels: component, enhancement

#643 Wrap Formik error with component
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/enhancers/withFormik.tsx
Labels: bug, component

#640 Fix NumberInput issues
  packages/react-component-library/src/components/NumberInput/EndAdornment.tsx
  packages/react-component-library/src/components/NumberInput/EndAdornmentButton.tsx
  packages/react-component-library/src/components/NumberInput/Input.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.stories.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.test.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.tsx
  packages/react-component-library/src/components/NumberInput/constants.ts
  packages/react-component-library/src/components/NumberInput/useFocus.ts
  packages/react-component-library/src/components/NumberInput/useValue.ts
Labels: bug, component

#628 Toast Component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_toast.scss
  packages/docs-site/src/library/pages/components/toast.md
  packages/react-component-library/package.json
  packages/react-component-library/src/components/Toast/Toast.stories.tsx
  packages/react-component-library/src/components/Toast/Toast.test.tsx
  packages/react-component-library/src/components/Toast/Toast.tsx
  packages/react-component-library/src/components/Toast/ToastProvider.tsx
  packages/react-component-library/src/components/Toast/index.ts
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
  yarn.lock
Labels: component, enhancement

#619 Add linting for commit messages
  .circleci/config.yml
  README.md
  commitlint.config.js
  docs/contributing.md
  package.json
  scripts/commitlint/index.js
  yarn.lock
Labels: devops, enhancement

#650 Adds new Standards icons to the icon library
  packages/icon-library/src/assets/standards/anchor.svg
  packages/icon-library/src/assets/standards/barrels.svg
  packages/icon-library/src/assets/standards/speed-fast.svg
  packages/icon-library/src/assets/standards/speed-med.svg
  packages/icon-library/src/assets/standards/speed-slow.svg
Labels: package/icon-library

#652 ci: Fix commitlint running on develop/master
  scripts/commitlint/index.js
Labels: bug, devops

#653 fix: add storybook webpack config to bundle fonts
  packages/react-component-library/.storybook/config.ts
  packages/react-component-library/.storybook/webpack.config.js
  packages/react-component-library/package.json
  yarn.lock
Labels: bug

#664 fix: add ability to inject custom CardFrame className
  packages/react-component-library/src/components/CardFrame/CardFrame.test.tsx
  packages/react-component-library/src/components/CardFrame/CardFrame.tsx
Labels: bug, component

#670 Release/2.2.0
  .circleci/config.yml
  README.md
  commitlint.config.js
  docs/contributing.md
  lerna.json
  package.json
  packages/css-framework/index.scss
  packages/css-framework/package.json
  packages/css-framework/src/components/_numberinput.scss
  packages/css-framework/src/components/_searchbar.scss
  packages/css-framework/src/components/_select.scss
  packages/css-framework/src/components/_table.scss
  packages/css-framework/src/components/_toast.scss
  packages/css-framework/src/fragments/_notification-panel.scss
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/components/toast.md
  packages/docs-site/src/library/pages/versions.md
  packages/eslint-config-react/package.json
  packages/fonts/package.json
  packages/icon-library/.svgrrc.js
  packages/icon-library/package.json
  packages/icon-library/src/assets/arrows/button-confirm.svg
  packages/icon-library/src/assets/standards/anchor.svg
  packages/icon-library/src/assets/standards/barrels.svg
  packages/icon-library/src/assets/standards/speed-fast.svg
  packages/icon-library/src/assets/standards/speed-med.svg
  packages/icon-library/src/assets/standards/speed-slow.svg
  packages/react-component-library/.storybook/config.ts
  packages/react-component-library/.storybook/webpack.config.js
  packages/react-component-library/package.json
  packages/react-component-library/src/components/CardFrame/CardFrame.test.tsx
  packages/react-component-library/src/components/CardFrame/CardFrame.tsx
  packages/react-component-library/src/components/NumberInput/EndAdornment.tsx
  packages/react-component-library/src/components/NumberInput/EndAdornmentButton.tsx
  packages/react-component-library/src/components/NumberInput/Footnote.tsx
  packages/react-component-library/src/components/NumberInput/Input.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.stories.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.test.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.tsx
  packages/react-component-library/src/components/NumberInput/StartAdornment.tsx
  packages/react-component-library/src/components/NumberInput/constants.ts
  packages/react-component-library/src/components/NumberInput/useFocus.ts
  packages/react-component-library/src/components/NumberInput/useValue.ts
  packages/react-component-library/src/components/Panel/Panel.test.tsx
  packages/react-component-library/src/components/Table/Table.test.tsx
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/components/Toast/Toast.stories.tsx
  packages/react-component-library/src/components/Toast/Toast.test.tsx
  packages/react-component-library/src/components/Toast/Toast.tsx
  packages/react-component-library/src/components/Toast/ToastProvider.tsx
  packages/react-component-library/src/components/Toast/index.ts
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/enhancers/withFormik.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.tsx
  packages/react-component-library/src/fragments/Masthead/useMastheadSearch.ts
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.tsx
  packages/react-component-library/src/index.ts
  scripts/commitlint/index.js
  yarn.lock
Labels: release

#677 fix: Add chore prefix for automated dependencies
  .dependabot/config.yml
Labels: bug, devops
