Repository Royal-Navy/design-system, pull requests merged in 2020-03, with the labels that each got.

#678 Alert component A11Y changes
  packages/css-framework/index.scss
  packages/css-framework/src/_config.scss
  packages/css-framework/src/base/_dev.scss
  packages/css-framework/src/base/_fonts.scss
  packages/css-framework/src/components/_alert.scss
  packages/css-framework/src/contexts/_light.scss
  packages/react-component-library/src/components/Alert/Alert.stories.tsx
  packages/react-component-library/src/components/Alert/Alert.test.tsx
  packages/react-component-library/src/components/Alert/Alert.tsx
Labels: package/component-library, package/css-framework

#693 feat(breadcrumbs): Add ability for one breadcrumb
  .circleci/config.yml
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/react-component-library/src/components/ScrollableNav/ScrollableNav.tsx
  packages/react-component-library/src/components/TabNav/TabNav.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.tsx
  packages/react-component-library/src/fragments/Masthead/MastheadNav.tsx
  packages/react-component-library/src/fragments/Sidebar/SidebarNav.tsx
  packages/react-component-library/src/types/Nav.ts
Labels: component, enhancement

#692 Update CI
  .circleci/config.yml
  docs/contributing.md
  package.json
  scripts/release-notes/fix-links.js
Labels: devops, enhancement

#696 ci: Fix workflow filters
  .circleci/config.yml
Labels: bug, devops

#694 Card Frame
  packages/css-framework/index.scss
  packages/css-framework/src/abstracts/functions/_index.scss
  packages/css-framework/src/abstracts/functions/_shadow.scss
  packages/css-framework/src/abstracts/mixins/_index.scss
  packages/css-framework/src/abstracts/mixins/_shadow.scss
  packages/css-framework/src/components/_badge.scss
  packages/css-framework/src/components/_card-frame.scss
Labels: package/component-library, package/css-framework

#700 ci: Update filter to ignore all branches
  .circleci/config.yml
Labels: bug, devops

#703 2.2.1
  CHANGELOG.md
  lerna.json
  packages/css-framework/CHANGELOG.md
  packages/css-framework/package.json
  packages/docs-site/CHANGELOG.md
  packages/docs-site/package.json
  packages/eslint-config-react/CHANGELOG.md
  packages/eslint-config-react/package.json
  packages/fonts/CHANGELOG.md
  packages/fonts/package.json
  packages/icon-library/CHANGELOG.md
  packages/icon-library/package.json
  packages/react-component-library/CHANGELOG.md
  packages/react-component-library/package.json
Labels: release

#704 Check version in NPM registry before publishing
  .circleci/config.yml
  scripts/npm/publish.js
Labels: bug, devops

#706 Streamline CircleCI jobs within workflows
  .circleci/config.yml
Labels: devops, enhancement

#707 Merging develop into master before delete
  .circleci/config.yml
  .dependabot/config.yml
  package.json
  packages/css-framework/index.scss
  packages/css-framework/src/_config.scss
  packages/css-framework/src/abstracts/functions/_index.scss
  packages/css-framework/src/abstracts/functions/_shadow.scss
  packages/css-framework/src/abstracts/mixins/_index.scss
  packages/css-framework/src/abstracts/mixins/_shadow.scss
  packages/css-framework/src/base/_dev.scss
  packages/css-framework/src/base/_fonts.scss
  packages/css-framework/src/components/_alert.scss
  packages/css-framework/src/components/_badge.scss
  packages/css-framework/src/components/_button.scss
  packages/css-framework/src/components/_card-frame.scss
  packages/css-framework/src/components/_checkbox.scss
  packages/css-framework/src/components/_radio.scss
  packages/css-framework/src/contexts/_light.scss
  packages/react-component-library/src/components/Alert/Alert.stories.tsx
  packages/react-component-library/src/components/Alert/Alert.test.tsx
  packages/react-component-library/src/components/Alert/Alert.tsx
  packages/react-component-library/src/components/Badge/Badge.stories.tsx
  packages/react-component-library/src/components/Badge/constants.ts
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/react-component-library/src/components/Button/Button.stories.tsx
  packages/react-component-library/src/components/Button/Button.tsx
  packages/react-component-library/src/components/ScrollableNav/ScrollableNav.tsx
  packages/react-component-library/src/components/TabNav/TabNav.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.tsx
  packages/react-component-library/src/fragments/Masthead/MastheadNav.tsx
  packages/react-component-library/src/fragments/Sidebar/SidebarNav.tsx
  packages/react-component-library/src/types/Nav.ts
  yarn.lock
Labels: devops, enhancement

#713 fix: Resolve 6.4.1 of acorn package
  package.json
Labels: devops, security

#716 Select component improvements
  packages/css-framework/src/components/_badge.scss
  packages/css-framework/src/components/_select.scss
  packages/react-component-library/src/components/Badge/Badge.stories.tsx
  packages/react-component-library/src/components/Badge/Badge.tsx
  packages/react-component-library/src/components/Badge/constants.ts
  packages/react-component-library/src/components/Select/Option.tsx
  packages/react-component-library/src/components/Select/SingleValue.tsx
Labels: package/component-library, package/css-framework

#724 fix: Remove SVGR generated icon-library exports (#723)
  packages/icon-library/package.json
Labels: bug

#726 Merge 2.2.2 back into master
  CHANGELOG.md
  lerna.json
  packages/css-framework/CHANGELOG.md
  packages/css-framework/package.json
  packages/docs-site/CHANGELOG.md
  packages/docs-site/package.json
  packages/eslint-config-react/CHANGELOG.md
  packages/eslint-config-react/package.json
  packages/fonts/CHANGELOG.md
  packages/fonts/package.json
  packages/icon-library/CHANGELOG.md
  packages/icon-library/package.json
  packages/react-component-library/CHANGELOG.md
  packages/react-component-library/package.json
Labels: Status: Blocked

#728 docs: Update contributing doc
  docs/contributing.md
Labels: Type: Enhancement

#717 Add ability to automate publishing of @next packages
  .circleci/config.yml
  package.json
Labels: Type: Devops, Type: Enhancement

#741 fix: Use minimist 1.2.5
  package.json
Labels: Type: Bug, Type: Devops

#740 ci: Add step to configure git before @next publish
  .circleci/config.yml
Labels: Type: Bug, Type: Devops

#747 Tweak prereleases and update docs
  .circleci/config.yml
  docs/contributing.md
  docs/release_checklist.md
  package.json
Labels: Type: Bug, Type: Devops

#751 Add data list component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_data-list.scss
  packages/react-component-library/src/components/DataList/DataList.stories.tsx
  packages/react-component-library/src/components/DataList/DataList.test.tsx
  packages/react-component-library/src/components/DataList/DataList.tsx
  packages/react-component-library/src/components/DataList/DataListItem.tsx
  packages/react-component-library/src/components/DataList/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: Package: css-framework, Package: react-component-library, Type: Component, Type: Enhancement

#738 feat(phase banner): increase font size to match Sketch file
  packages/css-framework/src/components/_phase-banner.scss
Labels: Package: css-framework, Package: react-component-library, Type: Component

#736 fix(breadcrumbs): match hover state to link hover state
  packages/css-framework/src/components/_breadcrumbs.scss
Labels: Package: css-framework, Package: react-component-library, Type: Component

#737 feat(date picker): decrease padding to match sketch file
  packages/css-framework/src/components/_date-picker.scss
  packages/css-framework/src/objects/_floating-box.scss
Labels: Package: css-framework, Package: react-component-library, Type: Component, Type: Enhancement

#749 docs: Update component library README
  packages/react-component-library/README.md
Labels: Package: react-component-library, Type: Enhancement

#752 fix(data list): remove overqualified selectors
  packages/css-framework/src/components/_data-list.scss
Labels: Package: css-framework, Type: Bug

#756 ci: Add commit message for lerna commands
  package.json
Labels: Type: Bug, Type: Devops

#760 chore: Add code owners
  .github/CODEOWNERS
Labels: Type: Devops

#762 ci: Set flag to not add git tag for prerelease
  package.json
Labels: Type: Devops

#763 Release/2.3
  CHANGELOG.md
  lerna.json
  packages/css-framework/CHANGELOG.md
  packages/css-framework/package.json
  packages/docs-site/CHANGELOG.md
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/versions.md
  packages/eslint-config-react/CHANGELOG.md
  packages/eslint-config-react/package.json
  packages/fonts/CHANGELOG.md
  packages/fonts/package.json
  packages/icon-library/CHANGELOG.md
  packages/icon-library/package.json
  packages/react-component-library/CHANGELOG.md
  packages/react-component-library/package.json
Labels: Release: v2

#765 Merge latest release back into master
  CHANGELOG.md
  lerna.json
  packages/css-framework/CHANGELOG.md
  packages/css-framework/package.json
  packages/docs-site/CHANGELOG.md
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/versions.md
  packages/eslint-config-react/CHANGELOG.md
  packages/eslint-config-react/package.json
  packages/fonts/CHANGELOG.md
  packages/fonts/package.json
  packages/icon-library/CHANGELOG.md
  packages/icon-library/package.json
  packages/react-component-library/CHANGELOG.md
  packages/react-component-library/package.json
Labels: Release: v2

#781 Update icon-library README
  packages/icon-library/README.md
  packages/react-component-library/README.md
Labels: Package: icon-library, Package: react-component-library, Type: Enhancement

#787 feat(fonts): Update README.md
  packages/fonts/README.md
Labels: Package: fonts, Type: Enhancement
