Repository Royal-Navy/design-system, pull requests merged in 2020-01, with the labels that each got.

#494 Refactor Masthead
  packages/css-framework/src/components/_scrollable-nav.scss
  packages/docs-site/src/library/pages/components/masthead.md
  packages/react-component-library/src/components/ScrollableNav/ScrollableNav.tsx
  packages/react-component-library/src/components/ScrollableNav/ScrollableNavItem.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/fragments/Masthead/Masthead.stories.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.test.tsx
  packages/react-component-library/src/fragments/Masthead/Masthead.tsx
  packages/react-component-library/src/fragments/Masthead/MastheadNav.tsx
  packages/react-component-library/src/fragments/Masthead/MastheadUser.tsx
  packages/react-component-library/src/fragments/Masthead/index.tsx
  packages/react-component-library/src/fragments/index.ts
  packages/react-component-library/src/index.ts
  packages/react-component-library/src/types/Nav.ts
Labels: component, documentation, enhancement

#506 Refactor Sidebar
  packages/docs-site/src/library/pages/components/sidebar.md
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  packages/react-component-library/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/react-component-library/src/components/Breadcrumbs/BreadcrumbsItem.tsx
  packages/react-component-library/src/components/TabNav/TabNav.tsx
  packages/react-component-library/src/components/TabNav/TabNavItem.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/fragments/NotificationPanel/Notification.tsx
  packages/react-component-library/src/fragments/Sidebar/Sidebar.stories.tsx
  packages/react-component-library/src/fragments/Sidebar/Sidebar.test.tsx
  packages/react-component-library/src/fragments/Sidebar/Sidebar.tsx
  packages/react-component-library/src/fragments/Sidebar/SidebarNav.tsx
  packages/react-component-library/src/fragments/Sidebar/SidebarNavItem.tsx
  packages/react-component-library/src/fragments/Sidebar/SidebarUser.tsx
  packages/react-component-library/src/fragments/Sidebar/index.tsx
  packages/react-component-library/src/fragments/index.ts
  packages/react-component-library/src/helpers.ts
  packages/react-component-library/src/index.ts
  packages/react-component-library/src/types/NavItems.d.ts
Labels: component, enhancement

#448 DatePicker Component
  packages/css-framework/index.scss
  packages/css-framework/src/components/_date-picker.scss
  packages/react-component-library/package.json
  packages/react-component-library/src/components/DatePicker/DatePicker.stories.tsx
  packages/react-component-library/src/components/DatePicker/DatePicker.test.tsx
  packages/react-component-library/src/components/DatePicker/DatePicker.tsx
  packages/react-component-library/src/components/DatePicker/Day.test.tsx
  packages/react-component-library/src/components/DatePicker/Day.tsx
  packages/react-component-library/src/components/DatePicker/Input.tsx
  packages/react-component-library/src/components/DatePicker/Month.tsx
  packages/react-component-library/src/components/DatePicker/NavButton.tsx
  packages/react-component-library/src/components/DatePicker/constants.ts
  packages/react-component-library/src/components/DatePicker/datepickerContext.ts
  packages/react-component-library/src/components/DatePicker/index.tsx
  packages/react-component-library/src/components/DatePicker/useOpenClose.ts
  packages/react-component-library/src/components/Popover/Popover.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
  yarn.lock
Labels: component, enhancement

#473 Add DatePicker Range Selection
  packages/css-framework/src/components/_date-picker.scss
  packages/react-component-library/src/components/DatePicker/DatePicker.stories.tsx
  packages/react-component-library/src/components/DatePicker/DatePicker.test.tsx
  packages/react-component-library/src/components/DatePicker/DatePicker.tsx
  packages/react-component-library/src/components/DatePicker/Month.tsx
Labels: component, enhancement

#513 Add components to v2 migration docs
  packages/docs-site/src/library/pages/get-started/development/v2-migration.md
Labels: documentation, v2

#517 Fix updated table state not rendering
  packages/react-component-library/src/components/Table/Table.test.tsx
  packages/react-component-library/src/components/Table/Table.tsx
  packages/react-component-library/src/components/Table/TableColumn.tsx
  packages/react-component-library/src/components/Table/useTableData.ts
Labels: bug, component

#521 Use dart sass instead of node-sass
  packages/reactapp/package.json
  yarn.lock
Labels: security

#524 Fix yarn types not generating dist types correctly
  packages/react-component-library/src/components/Nav/Nav.test.tsx
  packages/react-component-library/src/components/Nav/index.tsx
Labels: bug, component

#520 Refactor Badge to be consistent
  packages/react-component-library/src/components/Badge/Badge.stories.tsx
  packages/react-component-library/src/components/Badge/Badge.tsx
  packages/react-component-library/src/components/Badge/README.md
  packages/react-component-library/src/components/Badge/constants.ts
  packages/react-component-library/src/components/Badge/index.tsx
  packages/react-component-library/src/components/PhaseBanner/index.tsx
  packages/react-component-library/src/components/Select/Option.tsx
  packages/react-component-library/src/components/Select/SingleValue.tsx
  packages/react-component-library/src/components/Table/Table.stories.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, enhancement

#522 Change enum for object so that string can be used
  packages/react-component-library/src/components/Alert/Alert.tsx
  packages/react-component-library/src/components/Alert/constants.ts
  packages/react-component-library/src/components/Avatar/Avatar.tsx
  packages/react-component-library/src/components/Avatar/constants.ts
  packages/react-component-library/src/components/DatePicker/DatePicker.tsx
  packages/react-component-library/src/components/DatePicker/constants.ts
  packages/react-component-library/src/components/Popover/Popover.tsx
  packages/react-component-library/src/components/Popover/constants.ts
  packages/react-component-library/src/components/TabSet/ScrollButton.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
  packages/react-component-library/src/components/TabSet/constants.ts
  packages/react-component-library/src/components/Table/TableColumn.tsx
  packages/react-component-library/src/components/Table/constants.ts
  packages/react-component-library/src/components/Table/useTableData.ts
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.tsx
  packages/react-component-library/src/fragments/NotificationPanel/constants.ts
  packages/react-component-library/src/primitives/FloatingBox/FloatingBox.tsx
  packages/react-component-library/src/primitives/FloatingBox/constants.ts
Labels: component, enhancement

#528 Fix modal hide show from side effect
  packages/react-component-library/src/components/Dialog/Dialog.test.tsx
  packages/react-component-library/src/components/Modal/Footer.tsx
  packages/react-component-library/src/components/Modal/Header.tsx
  packages/react-component-library/src/components/Modal/Modal.test.tsx
  packages/react-component-library/src/components/Modal/Modal.tsx
  packages/react-component-library/src/components/Modal/useOpenClose.ts
Labels: bug, component

#533 Docs site Component page tabs
  packages/docs-site/src/components/presenters/post-article/_post-article.scss
Labels: Docs Site, bug

#532 Fix form components throwing errors in Storybook
  packages/react-component-library/src/components/Checkbox/Checkbox.stories.tsx
  packages/react-component-library/src/components/Checkbox/index.tsx
  packages/react-component-library/src/components/NumberInput/NumberInput.stories.tsx
  packages/react-component-library/src/components/Radio/Radio.stories.tsx
  packages/react-component-library/src/components/Switch/Switch.stories.tsx
  packages/react-component-library/src/components/TextArea/TextArea.stories.tsx
  packages/react-component-library/src/components/TextArea/TextArea.test.tsx
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
Labels: bug, component

#534 Delete storybook-react-input-state
  .circleci/config.yml
  package.json
  packages/react-component-library/package.json
  packages/react-component-library/src/components/TextInput/TextInput.stories.tsx
  packages/react-component-library/src/types/StorybookReactInputState.d.ts
  packages/storybook-react-input-state/.editorconfig
  packages/storybook-react-input-state/.gitignore
  packages/storybook-react-input-state/.storybook/config.js
  packages/storybook-react-input-state/.storybook/preview-head.html
  packages/storybook-react-input-state/README.md
  packages/storybook-react-input-state/package.json
  packages/storybook-react-input-state/src/State.js
  packages/storybook-react-input-state/src/State.test.jsx
  packages/storybook-react-input-state/src/Store.js
  packages/storybook-react-input-state/src/Store.test.js
  packages/storybook-react-input-state/src/index.js
  packages/storybook-react-input-state/stories/Input.jsx
  packages/storybook-react-input-state/stories/index.stories.jsx
  packages/storybook-react-input-state/webpack.config.js
  yarn.lock
Labels: devops, enhancement

#535 Remove redundant z-index
  packages/css-framework/src/components/_textinput.scss
Labels: bug, component

#537 Remove firebase deployments
  .circleci/config.yml
  packages/docs-site/.firebaserc
  packages/docs-site/.gitignore
  packages/docs-site/firebase.json
  packages/docs-site/package.json
  packages/react-component-library/.firebaserc
  packages/react-component-library/firebase.json
  yarn.lock
Labels: devops

#538 Remove ~/packages/reactapp
  package.json
  packages/reactapp/.env
  packages/reactapp/.gitignore
  packages/reactapp/README.md
  packages/reactapp/package.json
  packages/reactapp/public/favicon.ico
  packages/reactapp/public/index.html
  packages/reactapp/public/logo192.png
  packages/reactapp/public/logo512.png
  packages/reactapp/public/manifest.json
  packages/reactapp/public/robots.txt
  packages/reactapp/src/App.js
  packages/reactapp/src/Basic.js
  packages/reactapp/src/NumberForm.js
  packages/reactapp/src/index.js
Labels: devops, enhancement

#536 Use ...rest to drill props through Select wrapper
  packages/react-component-library/src/components/Select/Select.stories.tsx
  packages/react-component-library/src/components/Select/Select.test.tsx
  packages/react-component-library/src/components/Select/Select.tsx
Labels: bug, component

#539 Improve datepicker disabled styling
  packages/css-framework/src/components/_date-picker.scss
  packages/react-component-library/src/components/DatePicker/DatePicker.stories.tsx
  packages/react-component-library/src/components/DatePicker/DatePicker.test.tsx
  packages/react-component-library/src/components/DatePicker/DatePicker.tsx
Labels: bug, component

#543 DatePicker overlay appears behind modal
  packages/css-framework/src/components/_date-picker.scss
  packages/react-component-library/src/components/DatePicker/DatePicker.tsx
Labels: bug, component

#540 Refactor Circle CI YAML
  .circleci/config.yml
Labels: devops, enhancement

#556 Prevent className prop stripping Select component base class
  packages/react-component-library/src/components/Select/Select.tsx
Labels: bug, component

#512 Add date picker docs
  packages/docs-site/src/library/images/components/date-picker/anatomy.svg
  packages/docs-site/src/library/images/components/date-picker/component.svg
  packages/docs-site/src/library/images/components/date-picker/daterangecomponent.svg
  packages/docs-site/src/library/pages/components/date-picker.md
  packages/react-component-library/src/components/DatePicker/DatePicker.stories.tsx
  packages/react-component-library/src/components/DatePicker/DatePicker.test.tsx
  packages/react-component-library/src/components/DatePicker/DatePicker.tsx
  packages/react-component-library/src/components/DatePicker/Day.tsx
  packages/react-component-library/src/components/DatePicker/Input.tsx
  packages/react-component-library/src/components/DatePicker/Month.tsx
  packages/react-component-library/src/components/DatePicker/index.tsx
  packages/react-component-library/src/components/DatePicker/useOpenClose.ts
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, documentation

#559 Use icon library for breadcrumb chevron
  packages/css-framework/src/components/_breadcrumbs.scss
  packages/react-component-library/src/components/Breadcrumbs/BreadcrumbsItem.tsx
  packages/react-component-library/src/components/Breadcrumbs/images/separator.svg
Labels: bug

#510 Add card frame with docs
  packages/css-framework/src/components/_card-frame.scss
  packages/docs-site/src/library/images/components/card/anatomy.svg
  packages/docs-site/src/library/pages/components/card-frame.md
  packages/react-component-library/src/components/CardFrame/CardFrame.stories.tsx
  packages/react-component-library/src/components/CardFrame/CardFrame.test.tsx
  packages/react-component-library/src/components/CardFrame/CardFrame.tsx
  packages/react-component-library/src/components/CardFrame/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, documentation

#557 Make react-component-library tree shakeable downstream
  lerna.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/eslint-config-react/package.json
  packages/icon-library/package.json
  packages/react-component-library/.babelrc
  packages/react-component-library/package.json
  packages/react-component-library/webpack/analyze.js
  packages/react-component-library/webpack/dev.js
  packages/react-component-library/webpack/prod.js
Labels: devops, enhancement

#560 Adds popover design docs and images
  packages/docs-site/src/library/images/components/popover/Anatomy.svg
  packages/docs-site/src/library/images/components/popover/Component.svg
  packages/docs-site/src/library/pages/components/popover.md
Labels: Docs Site, documentation

#562 Skip test with race condition
  packages/react-component-library/src/components/Popover/Popover.test.tsx
Labels: bug

#547 Add Chromatic QA to CI
  .circleci/config.yml
  README.md
  packages/react-component-library/package.json
  yarn.lock
Labels: devops, enhancement

#558 Remove CSS class unit tests
  packages/react-component-library/src/components/Alert/Alert.stories.tsx
  packages/react-component-library/src/components/Alert/Alert.test.tsx
  packages/react-component-library/src/components/Button/Button.test.tsx
  packages/react-component-library/src/components/Nav/Nav.test.tsx
  packages/react-component-library/src/components/Popover/Popover.test.tsx
  packages/react-component-library/src/components/RangeSlider/RangeSlider.test.tsx
  packages/react-component-library/src/components/Select/Select.test.tsx
  packages/react-component-library/src/components/Table/Table.test.tsx
  packages/react-component-library/src/fragments/NotificationPanel/NotificationPanel.test.tsx
  packages/react-component-library/src/primitives/FloatingBox/FloatingBox.stories.tsx
  packages/react-component-library/src/primitives/FloatingBox/FloatingBox.test.tsx
Labels: component, enhancement

#565 Change Alert examples to different structure
  packages/react-component-library/src/components/Alert/Alert.stories.tsx
Labels: component, enhancement

#566 Refactor Avatar Storybook examples
  packages/react-component-library/src/components/Avatar/Avatar.stories.tsx
Labels: component, enhancement

#567 Refactor Badge Storybook examples
  packages/react-component-library/src/components/Badge/Badge.stories.tsx
  packages/react-component-library/src/components/Badge/Badge.tsx
Labels: component, enhancement

#568 Upgrade dependencies
  package.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/eslint-config-react/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
  yarn.lock
Labels: devops, security

#571 Add @royalnavy/fonts package
  .circleci/config.yml
  lerna.json
  package.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/docs-site/src/library/pages/get-started/development/installation.md
  packages/eslint-config-react/package.json
  packages/fonts/LICENCE
  packages/fonts/README.md
  packages/fonts/assets/Lato-Black.ttf
  packages/fonts/assets/Lato-BlackItalic.ttf
  packages/fonts/assets/Lato-Bold.ttf
  packages/fonts/assets/Lato-BoldItalic.ttf
  packages/fonts/assets/Lato-Hairline.ttf
  packages/fonts/assets/Lato-HairlineItalic.ttf
  packages/fonts/assets/Lato-Heavy.ttf
  packages/fonts/assets/Lato-HeavyItalic.ttf
  packages/fonts/assets/Lato-Italic.ttf
  packages/fonts/assets/Lato-Light.ttf
  packages/fonts/assets/Lato-LightItalic.ttf
  packages/fonts/assets/Lato-Medium.ttf
  packages/fonts/assets/Lato-MediumItalic.ttf
  packages/fonts/assets/Lato-Regular.ttf
  packages/fonts/assets/Lato-Semibold.ttf
  packages/fonts/assets/Lato-SemiboldItalic.ttf
  packages/fonts/assets/Lato-Thin.ttf
  packages/fonts/assets/Lato-ThinItalic.ttf
  packages/fonts/index.css
  packages/fonts/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
Labels: enhancement

#584 Fix indentation in CircleCI config workflow
  .circleci/config.yml
Labels: bug, devops

#569 Refactor Tooltip stories to use new structure
  packages/react-component-library/src/components/Tooltip/Tooltip.stories.tsx
Labels: component, enhancement

#570 Refactor Storybook examples for Button
  packages/react-component-library/src/components/Button/Button.stories.tsx
  packages/react-component-library/src/components/Button/Button.tsx
  packages/react-component-library/src/components/Button/constants.ts
  packages/react-component-library/src/components/Button/index.tsx
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: component, enhancement

#581 Fix Checkbox documentation
  packages/docs-site/src/library/pages/components/form/checkbox.md
Labels: component, documentation

#582 Refactor stories to use new structure
  packages/react-component-library/src/components/ButtonGroup/ButtonGroup.stories.tsx
  packages/react-component-library/src/components/DatePicker/DatePicker.stories.tsx
  packages/react-component-library/src/components/Dialog/Dialog.stories.tsx
  packages/react-component-library/src/components/Dropdown/Dropdown.stories.tsx
  packages/react-component-library/src/components/Modal/Modal.stories.tsx
  packages/react-component-library/src/components/PhaseBanner/PhaseBanner.stories.tsx
  packages/react-component-library/src/components/Popover/Popover.stories.tsx
  packages/react-component-library/src/components/RangeSlider/RangeSlider.stories.tsx
  packages/react-component-library/src/components/Select/Select.stories.tsx
  packages/react-component-library/src/components/Switch/Switch.stories.tsx
  packages/react-component-library/src/components/Table/Table.stories.tsx
  packages/react-component-library/src/types/Switch.d.ts
Labels: component, enhancement

#583 Use React.Children.map over children.map
  packages/react-component-library/src/components/Table/Table.tsx
Labels: component, enhancement

#590 Update content description frontmatter
  packages/docs-site/src/library/pages/get-started/development/index.md
Labels: documentation

#588 Add dependabot config to repo
  .dependabot/config.yml
Labels: devops

#586 Update TextArea interface
  packages/react-component-library/src/components/TextArea/index.tsx
Labels: bug, component

#585 Remove focus box-shadow from TabSet
  packages/css-framework/src/components/_tab-set.scss
Labels: bug, component

#589 Fix Popover test intermittently failing
  packages/react-component-library/src/components/Popover/Popover.stories.tsx
  packages/react-component-library/src/components/Popover/Popover.test.tsx
  packages/react-component-library/src/components/Popover/index.ts
  packages/react-component-library/src/components/index.ts
  packages/react-component-library/src/index.ts
Labels: bug, component

#591 Remove array cast in SidebarNav
  packages/react-component-library/src/fragments/Sidebar/SidebarNav.tsx
Labels: component

#587 Stop TabSet change submitting parent form
  packages/react-component-library/src/components/TabSet/TabItem.tsx
  packages/react-component-library/src/components/TabSet/TabSet.test.tsx
Labels: bug, component

#604 Release/2.1.1
  lerna.json
  packages/css-framework/package.json
  packages/docs-site/package.json
  packages/eslint-config-react/package.json
  packages/fonts/package.json
  packages/icon-library/package.json
  packages/react-component-library/package.json
Labels: release
